-- IBMP Leads Import - Batch 07
-- Records: 100
-- Generated: 2025-09-29T13:18:26.731Z

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Alhanof aref alshamea',
    'Sahrnzly',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473259","content":"texted , gave details","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Likitha',
    'Likithagundan',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473794","content":"called busy , later have to call//not getting connected//whats app done//not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr.Ahefaz sheikh....',
    'Ahefaz.sheikh5',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-175915101847319","content":"not connected//not connected//whats app kiya//not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ziyoda',
    'Ziyodabekmuratovna',
    NULL,
    'UZ',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473755","content":"no whats app , email sent//","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'kikiiii',
    'Keerthikeerthi0205',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Not Interested',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473980","content":"call ended","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'ع',
    'Ammarclub04',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-17591510184734","content":"asked to call later// not attending//NOT ATTENDING","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Darshan jain',
    'Darshankusanal1008',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Not Interested',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473936","content":"call kiya , cut kardera//","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'هيبة يمانيه',
    'Ghadeern639',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473510","content":"not connected//whats app kiya","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Акбар Азамхонов',
    'Aa.azamxonov',
    NULL,
    'UZ',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473465","content":"no whats app , email sent","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Salem Almahrooqi',
    'Salmos',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473718","content":"whats app sent// plastic surgery","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ali Abdulrahman',
    'Alidfallah12',
    NULL,
    'SD',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473562","content":"not attending call.// whats app sent//arabic chatting//stiill not replied","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Megharaj Wankar',
    'Wankarmegharaj608',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Not Interested',
    'Satish',
    'IBMP',
    '[{"id":"note-175915101847365","content":"50,000 asking for pg diploma","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'dr.__sahil',
    'Prajapatisahil9817',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Not Interested',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473827","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Shashank Kacha',
    'Shashankdkacha',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473351","content":"not answered 2 times //ayush final year","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Amna AL-Junaid',
    'Amoon1999da',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473891","content":"not connecting///3 times did//arabic sent//not answering //not replied in whts ap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr.Atharv',
    'Atharavsawant',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Not Interested',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473335","content":"not connecting///2 times did","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    '𝓟𝓪𝓿𝓲𝓲',
    'Pavi23102003',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473808","content":"4 times called, not answered// droppped voice message//not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'RDGRIN Daluwaththa',
    'Rdgrindaluwaththa',
    '+94763176593',
    'LK',
    'Others',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473333","content":"call attend nahi kiya//whats app done//ot attending","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'William Tyndale Nootalapati',
    'Tyndale16',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473274","content":"call kiya 3 times","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ramadan Aly',
    'Ramadanaly2011966',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473606","content":"speaking in other language whats app kiya","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Suresh Upadhyay',
    'Upadhyaysuresh511',
    NULL,
    'NP',
    'Others',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473203","content":"called asked to text//not answering, text kiya//call not attending","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'صالح جبوخ',
    'Saleh.salehll2088',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473354","content":"whats app done in arabic/clinical pharma//whats app done","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Saif Agiz',
    'Swoord46',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Warm',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473305","content":"call done, sounds good, sent details.//6 mins call done, sounds good","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Wessam Shamsan',
    'Wessamshmsan',
    NULL,
    'YE',
    'Others',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473496","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Каримова Гулноз',
    'Gorgeousdoctor',
    NULL,
    'UZ',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473709","content":"No whats app.......","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdul Rasheed Mohammed Inthikaf',
    'Inthikaf17087',
    NULL,
    'LK',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473809","content":"wts app done//not replied so did in germany language","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ashhar Ahamed',
    'Ashharahamed1',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018473620","content":"Switch off text in whats up // Switch off // Switch off // rnr","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sri Hari Yadav',
    'Sreehari295',
    NULL,
    'US',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018473790","content":"Dr said he is busy ask to text in whats up // CALL ANSWER AND DISCONNECTED // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdulrahman Mostafa',
    'Dr_abd1982',
    '+97433091750',
    'QA',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-175915101847322","content":"RNR text Dr in whats up Dr text back in whats said he is busy and ask yto share with the details . Clinical cardiology for 9 months First option details shared in whats up waiting for response // Paym...","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Adam',
    'Rayanadamson1980',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018473364","content":"RNR text Dr in whats up // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Logeshkumar Ravichandran',
    'Ravichandranlogeshkumar',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Warm',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018473606","content":"Said Dr is FMG ask to share the cv in whats up waiting infromed Dr he is eligibel for online course not in offline . Dr is intrested in fellowship in cretical care hence details and demo class details...","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'عبدالله الطيب',
    'Altaeib5',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018473881","content":"RNR text in whats up // Dr answer and disconnected the call //RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'DrNagsen Shobha Dilip Lokhande',
    'Lokhandenagsen458',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018473540","content":"Called to Dr he answered and disconnected the call text in whats up // Busy tone // Busy tone","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'وسام عبدالملك',
    'Wesam.aqel.77',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Warm',
    'Roshan',
    'IBMP',
    '[{"id":"note-175915101847391","content":"Called to Dr said she is not understanding with me and ask to text in whats up // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr Aashish',
    'Aashishthakur234',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Warm',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018473707","content":"(9877543917 ) Called to Dr said he is looking for pgd in cardiology and ask to share the details in whats up . shared details for PG Diploma clinical cardiology in whats waiting for response // said h...","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr.Aamir Abdul Majeed',
    'Aamiram1766',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018473968","content":"Dr said not intrested due to finacial issue","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Seven',
    'Shrivasaadi1004',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018473126","content":"Call hang up connect on whataap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Viv',
    'Vivekprasaddas123',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Warm',
    'Aslam',
    'IBMP',
    '[{"id":"note-175915101847352","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Nagwa Yousef Moro',
    'Dr.mohamedelsherbiny64',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-175915101847388","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Awad Abdelrazig elmahi Ahmed',
    'Awad5aammasub',
    NULL,
    'SD',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018473320","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ziad Hussein',
    'Superziad2000',
    NULL,
    'KW',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018473421","content":"Connect on whataap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohd Almuqayad',
    'Mohdmuqayad',
    NULL,
    'US',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018473158","content":"Connect on whataap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sobirjon Tursunov',
    'Di.206b.tursunovsobirjon04',
    NULL,
    'UZ',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018473843","content":"Connect on what Aap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hager Mostafa',
    'Hagermostafa0865',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018473363","content":"Connect on what Aap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Lâm Phan',
    'Drlamphan',
    '+84973551211',
    'VN',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-175915101847318","content":"Call Hang Up No Whataap to connect","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdullah Radi Mohammed salem',
    'Abdallaradi4',
    NULL,
    'EG',
    'Others',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018473367","content":"Brochurtes send he is speaking Arabic","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ferial Ali',
    'Fuada2652',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018473686","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'SåRü',
    'Saruxingh',
    NULL,
    'NP',
    'Others',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-175915101847331","content":"Connect on what aap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ajit Kishore',
    'Aj.ki2010',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018473310","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hassan Alalawi',
    'Halalawi84',
    NULL,
    'US',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473422","content":"whats app doing","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'wafae',
    'Aitbelaid.wafae',
    NULL,
    'MA',
    'MD/MS/DNB',
    'Robotic surgery',
    'Warm',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473639","content":"text kiya//text kiya","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed-Amine Malki',
    'Aminemalki14',
    NULL,
    'MA',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473394","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Luiz Gustavo Bueno',
    'Lgobueno',
    NULL,
    'BR',
    'MD/MS/DNB',
    'Robotic surgery',
    'Not Interested',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473912","content":"call attended but cut kiya","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmad Abdullah',
    'Lotfy1012010',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-175915101847333","content":"whats app done","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohammed Ahmed Zedan',
    'Drzeezooo3',
    NULL,
    'US',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473712","content":"whats app kiya//text kiya// in arabic","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hind Bourja',
    'Hindou.009',
    NULL,
    'MA',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473361","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'ACM Musthaq',
    'Drmusthaq',
    '+94773591154',
    'LK',
    'MD/MS/DNB',
    'Robotic surgery',
    'Not Interested',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473868","content":"need details, gyeno, laproscop","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdelrahman Lotfy',
    'Abdelrahman.s.ahmed',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473773","content":"details gave","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hakob Tatosyan',
    'Hakobta',
    '+37477888844',
    'AM',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473158","content":"busy , said to call back// whats app call kiya,","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr abdelsalam',
    'Urologye',
    NULL,
    NULL,
    'Others',
    'General Medicine',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018473899","content":"Mail sent for whats up number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Arun Shah',
    'Arunshahmanipal08',
    NULL,
    'NP',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473393","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mamatha',
    NULL,
    '+919727087772',
    'IN',
    'AYUSH',
    'Cosmetology',
    'Not Interested',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473314","content":"Called //intrested in pg diploma asthetic and cosmetology","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr Waseem Ahmad',
    'Waseemahmad69',
    NULL,
    'IN',
    'AYUSH',
    'Fellowship Psyc',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473759","content":"call done, sent details","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr. Poonam Prajapati',
    'Drpoonamrprajapati',
    NULL,
    'IN',
    'AYUSH',
    'Fellowship Psyc',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473208","content":"whats app done","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr. Shehab Ahmed',
    'Shehabalmahdi1998',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473983","content":"whats app done","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr.Ajay Nagzarkar',
    'Drajaynagzarkar',
    NULL,
    'IN',
    'AYUSH',
    'Fellowship Psyc',
    'Not Interested',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473772","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'DR.Sagarnandini',
    'Sagarnandini5',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Fellowship Psyc',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473694","content":"sent whats app","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr.Tesita',
    'Tesita.sherry623',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Fellowship Psyc',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473205","content":"sent whats app","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Eyad Mohamed',
    'Eyadmohamedrc',
    '+201558735633',
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473721","content":"sent whats app","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ghada Alsayed',
    'Ghadoosh.m.1996',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Fellowship Psyc',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473439","content":"whats app done","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hossam Farid',
    'Hossamfarid',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473158","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hossam Mohammed',
    'Hossamawad2020',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473233","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Jayalaxmi Roja',
    'Jayalaxmiroja999',
    '+61450700369',
    'AU',
    'MBBS/ FMG',
    'Fellowship Psyc',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473125","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Khalid Mohamed Aly El-Tamawey',
    'Khalid_eltamawey',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473837","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mazen Ghaleb',
    'Ghalebmazen44',
    NULL,
    'US',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473824","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Mostafa',
    'Drmam1978',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473846","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Nahla',
    'Nahlatareksadek11',
    NULL,
    'EG',
    'Others',
    'Psychiatric ads',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-175915101847368","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mssadek Abderrahim',
    'Amssadek2006',
    NULL,
    'MA',
    'Others',
    'Fellowship Psyc',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473276","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Pradeep Pandey',
    'Pradeep_sant1',
    NULL,
    'NP',
    'MD/MS/DNB',
    'Fellowship Psyc',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473246","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Pranyata',
    'Pdlpranyata2',
    NULL,
    'NP',
    'MBBS/ FMG',
    'Fellowship Psyc',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473776","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Shirsendu Ghosh',
    'Dr.shirsendughosh',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Fellowship Psyc',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473988","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Om Harihar',
    'Hariomharihar9099',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473461","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mehdi Tamir',
    'Mehdi.tamir',
    NULL,
    'MA',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473393","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dania Almujahed',
    'Daldal700mujahed',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-175915101847358","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Walaa Fawzi',
    'Walaafawzi841',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473394","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr.NAFIL MHD',
    'Nafilmuhammed1999',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473590","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr Dinesh Chandra Bhatt',
    'D8126048547',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473305","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'فهمي علي سرحان',
    'Fahmialisarhan',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473329","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sabeer',
    'Kolikerisabeer97',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473187","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Gamal',
    'Alshawam',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473505","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Subash Chaminda',
    'Eschaminda',
    '+94763826832',
    'LK',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473500","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Нодир Фармонов',
    'Farmonov.79',
    NULL,
    'UZ',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473640","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hesham Talhan',
    'Heshamtalhan',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473183","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mehdi',
    'Bouroyene',
    NULL,
    'MA',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473507","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdelrahman_vvgs',
    'Bedo_debaky',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473396","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'حسين محمد علي علوان',
    'Hussainalzazai',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473275","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr Tapi Koma',
    'Drtapikoma',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473745","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Khawaja Ehtesham Ahmad',
    'Drsham786',
    NULL,
    'SA',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473738","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Amin Khimakham',
    'Dr.ma.cardio',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473923","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr Adil Bagwan',
    'Adilbagwan6149',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473240","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);
