-- IBMP Leads Import - Batch 08
-- Records: 100
-- Generated: 2025-09-29T13:18:26.731Z

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Nitesh Bhandarkar',
    'Drnitesh91',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473492","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Navaraj Paudel',
    'Drnavarajdm',
    NULL,
    'NP',
    'Others',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-175915101847324","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Islam Abdelwahid',
    'Ahmedislam043',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473228","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr BHAMIDIPATI VENKATARAO',
    'Venkat_bh',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018473450","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.473Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    '𝑫𝒉𝒂𝒓𝒔𝒉𝒊𝒏𝒊',
    'Dharshini7804',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018474613","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Rohan Ekanayake',
    'Rohanhlk',
    '+94777922264',
    'LK',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018474264","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Moh.Kh77',
    'Mohaned.doman.eg',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018474438","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Murali Dharan',
    'Drmurali75',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018474273","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Enosh Katta',
    'Enosh.k7777',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018474998","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Hassan',
    'Mh2610158292',
    NULL,
    'EG',
    'Others',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018474711","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sid jain',
    'Drjainsm',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018474382","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'jouhayna',
    'Jouhafdl',
    NULL,
    'MA',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474839","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Bady Hagir Osman',
    'Osmanbady2014',
    NULL,
    'SA',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474224","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Babayev Jumabek',
    'Jumabekboboyev',
    NULL,
    'UZ',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474611","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Yubraj Budha',
    'Coalblack99',
    NULL,
    'NP',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474736","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Thilini Dilhani',
    'Thilinidilhani1000',
    '+94776656339',
    'LK',
    'Others',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101847445","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'عبدالرحمن محمد غالب السلطان',
    'Abd7700ww9',
    NULL,
    'YE',
    'Others',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474721","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Satya Narayan Yadav',
    'Drsnyadav372',
    '+97333181183',
    'BH',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474607","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'REKHHA',
    'Rekha010386',
    NULL,
    'IN',
    'Others',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101847435","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Bipana Pandey',
    'Pandeybipana',
    NULL,
    'NP',
    'Others',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474405","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'DrSonal Rai',
    'Rai_sonal',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474155","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    '_Vejuli_',
    'Vejuli.matreja',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474422","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Kattel Vivek Kattel',
    'Vivekkattel',
    NULL,
    'NP',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474801","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'dr.nishant kumar jha',
    'Onlyforunishant2011',
    NULL,
    'IN',
    'Others',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474202","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr Faruk Ahmed',
    'Faruk1989ahmed',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474291","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr Ayush Aggarwal',
    'Ayushmohan02',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474258","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Harpreet Singh',
    'Sdgh',
    NULL,
    'IN',
    'AYUSH',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474336","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Yashwant Rathor',
    'Yashwantrathor97',
    NULL,
    'IN',
    'AYUSH',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474301","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'vivek',
    'Vivekfarmgate',
    NULL,
    'IN',
    'Others',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474220","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sara Aldriny',
    'Saraaldriny',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474442","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr. Sushil Chaudhary',
    'Aman.sushil',
    NULL,
    'IN',
    'AYUSH',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-17591510184742","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abeer',
    'Abeer.265',
    NULL,
    'IN',
    'AYUSH',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474256","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'DrMarwa RaGab',
    'Marw0702',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474896","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'د.عبدالسلام أحمد العقلاني',
    'A10313207',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474851","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohammed Khalid Saeed Saleh',
    'Mk5159861',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474606","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'M Tarun Kumar',
    'Yoshithkumar01',
    NULL,
    'IN',
    'AYUSH',
    'Cardiology ad',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474643","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Muskan',
    'Manishako2003',
    NULL,
    'IN',
    'Others',
    'Cardiology ad',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474660","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohammedaasif Ansari',
    'Dr_msansari92',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Cardiology ad',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474478","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Permeshwar Tandel',
    'Manntandel240729',
    NULL,
    'IN',
    'Others',
    'Cardiology ad',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474569","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mr.pôrs(ə)lən',
    'Saidusabeersaidu',
    NULL,
    'AE',
    'Others',
    'Cardiology ad',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474453","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohammed Abdelshakour',
    'Dr_mohammedabdelshakour',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Critical care a',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474873","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr Shweta Mourya',
    'Shwetamaurya9916',
    '9916607724',
    'India',
    'MD/MS/DNB',
    'PGD OBS GYNAE',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474686","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Amjad Shehab',
    'Amjadshehab2001',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Cardiology ad',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101847447","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Kundan kumar',
    'Sabkundan80',
    NULL,
    'IN',
    'Others',
    'Cardiology ad',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101847483","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Masadul Sk',
    'Sksarip9083046',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Critical care a',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474197","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohammed Abdelshakour',
    'Dr_mohammedabdelshakour',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Critical care a',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474502","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sunil Pandey',
    'Sunilmbbs2016',
    NULL,
    'NP',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474466","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sarvar Khojiev',
    'Khojievsarvar',
    NULL,
    'UZ',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474229","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmad Ibrahem',
    'Ahmad909.ai',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Critical care a',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474298","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Saad Emad',
    'Saademad3377',
    NULL,
    'EG',
    'Others',
    'Critical care a',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474654","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abhishek Anand',
    'Abhianand55358',
    NULL,
    'IN',
    'Others',
    'Reproductive me',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474146","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Elhindi',
    'Hafizelhindi',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474421","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'DR/ Malak (◕ᴗ◕✿)',
    'Malakzidan206',
    NULL,
    'EG',
    'Others',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474182","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohammad Zain Khan',
    'Zainkhn55576',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474862","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Shiamaa Aboelfath',
    'Shymoo2013',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474479","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdou Mahmoud Abdou',
    'Dr.abdoumahmoudsurgeon1986',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101847448","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdallah Saad',
    'Dally201515',
    NULL,
    'EG',
    'Others',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474559","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'DrSatyabrat Gadanayak',
    'Drgadanayak',
    NULL,
    'AE',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474773","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Bahaa',
    'Abahaa0503',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474714","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Gerguis Besmark',
    'Gerguis_besmark',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474153","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'هشام الكمالي',
    'Hishamalkamali',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474851","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Majed Abdulmajed',
    'Phmajed2017',
    NULL,
    'YE',
    'Others',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474357","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    '𝓓𝓡.𝓜𝓤𝓡𝓐𝓓 𝓞𝓜𝓐𝓡 𝓢𝓐𝓔𝓔𝓓 𝓐𝓛-𝓗𝓔𝓝𝓓�',
    'Murad.badhdh',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474655","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ashwa Poorva Priyadarshini',
    'Ashuag372',
    NULL,
    'AM',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474904","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Manohar',
    'Bmanohar2502',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474998","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Abd El-Rehim',
    'Mohammed.sadek1991',
    NULL,
    NULL,
    'Others',
    'Robotic Surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474312","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Biloliddin Sharobidinov',
    'Sharobidinovb2021',
    NULL,
    NULL,
    'Others',
    'Robotic Surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474113","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmad Izani',
    'Ahmadizanimd',
    NULL,
    NULL,
    'Others',
    'Robotic Surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474170","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Chandrabhan Patel',
    'Chandrabhanpatel12',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018474907","content":"Getting busy","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Muhamd Amer',
    'Mekoo.amer',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018474172","content":"Call hang up","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ashish Gupta',
    'Ashish.gupta428',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018474651","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Elizabeth Cherian',
    'Echerian309',
    NULL,
    'US',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018474414","content":"She make an genaral inqirey","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'MAJID KARIM',
    'Majidkarim370',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018474714","content":"Call Back After 1/2 Not Ans","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr. Vishwajit Prakash Patil',
    'Vishwajitpatil300300',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018474392","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'drraghunarayan',
    'Rncoolguy',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018474524","content":"Not Ans","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Azizbek Chorshanbiyev',
    'Lion49518',
    NULL,
    'UZ',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018474688","content":"Not Connecting","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr. Niraj Sagar',
    'Nirajsagar2006',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018474577","content":"MBBS 3 Years Exp","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'joy',
    'Edurivictoria1011',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018474221","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Pinkal Rana',
    'Pinkalrana882',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018474182","content":"call done need details","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdelrahman ELGENDY',
    'Pedoelgendy',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-175915101847497","content":"whats app done","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr Bahar Liza Fredie',
    'Silynmili',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018474594","content":"said to call back","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Lokesh Loke',
    'Lokesh.123456',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018474989","content":"whats app did replied please check","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Нодир Уринбоев',
    'Urinboevnodirbek1998',
    NULL,
    'UZ',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018474375","content":"texted in german","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'DrBhuvana',
    'Bhuvanarc7',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Enrolled',
    'Satish',
    'IBMP',
    '[{"id":"note-17591510184744","content":"done on 27 sept 2025 3700 usd","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'ASHISH YADAV',
    'Gayadav0021',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018474116","content":"general medicine doing","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr sania muzaffar',
    'Drsaniamuzaffar68',
    NULL,
    'US',
    'AYUSH',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018474565","content":"no whats app","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr Sairab Alam Butt',
    'Shababalam885',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Hot',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018474204","content":"mbbs done from jammu, 2 yrs exp after mbbs, needs interventional","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'صلاح قادري',
    'Salahqadery1',
    NULL,
    'US',
    'Others',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018474304","content":"arabic texting","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'S.A. Hafeez Khan',
    'Mdhafeezk99',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474246","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohai Eddine Hadit',
    'Mohihadit77',
    NULL,
    'MA',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474982","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'NADA NAZEH SHARYAN MOHAMMED DUGHAISH',
    'Nadanazeh89',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474824","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mahmood Alshaari',
    'Alshamash1000',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474852","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'مصطفى محمود الكحصة',
    'Alkahsah.mostafa',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474741","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Safaa Alnahass',
    'Hamadanoory37',
    NULL,
    'SA',
    'Others',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474248","content":"speaking arabic","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr Rupesh Rathod',
    'Sonofpadmavati',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474777","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'شريف أمير على',
    'Shah_119',
    NULL,
    'ZA',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474903","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Chaitanya Pardeshi',
    'Chaitanyapardeshi20',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474165","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'عبد الرحمن محمود',
    'Hnurse400',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474344","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hnin Alansi',
    'Hninalansi',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474137","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sunday isitor',
    'Sisitor',
    NULL,
    'NG',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474652","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);
