-- IBMP Leads Import - Batch 10
-- Records: 100
-- Generated: 2025-09-29T13:18:26.732Z

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Rami Yousef',
    'Dr_rami_iusef',
    NULL,
    'UA',
    'Others',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475879","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Natalya Baghumyan',
    'Nataliebaghumyan',
    '+37494866468',
    'AM',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475350","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Eliseu Perius',
    'Periusmed',
    '+51992957798',
    'BR',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475265","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohammed Shosha',
    'Dr.mshosha.ms',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475932","content":"connect on what aap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Amar Ashraf',
    'Ammar123ashraf12345',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475185","content":"connect on what aap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Osama',
    'Mohamedosamagamal',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475474","content":"connect on what aap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Shawky Mohammed Elsherif',
    'Ahmedelsherif1959',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Hot',
    'Aslam',
    'IBMP',
    '[{"id":"note-175915101847523","content":"connect on what aap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Hassan',
    'Mohamed.hasan2003',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475792","content":"connect on what aap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdelrahman gamal saleh',
    'Abdelrahmansaleh90',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475744","content":"connect on what aap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Jaeger',
    'Siddiqjonkuziyev',
    NULL,
    'UZ',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475991","content":"He is student","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Christian Wabene',
    'Chr.wabenn',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475669","content":"connect on what aap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Reda Abdelfattah Salem',
    'Redashahin',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475254","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Bhishman Thevarajah',
    'Bhishmant',
    '+94777738017',
    'LK',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475292","content":"connect on what aap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Ismail Hassan Ismail Ibrahim',
    'Ahmed_ihi',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475506","content":"connect on what aap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Efinvi Farzona',
    'Dr_farzona',
    NULL,
    'UZ',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475109","content":"connect on what aap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Casey Ooi',
    'Caseytcooi',
    '+60195118888',
    'MY',
    'MD/MS/DNB',
    'Robotic surgery',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475660","content":"Next Year looking for","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdullah Galal',
    'Dr_abdullah_galal',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475885","content":"connect on what aap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr Younes Benazzouz',
    'Younesbenazzouz88',
    NULL,
    'MA',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475977","content":"connect on what aap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Nazeeh Botros',
    'Nwbotros',
    NULL,
    'EG',
    'Others',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-175915101847588","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Rozana T Eltahan',
    'Rozanatalat5102005',
    NULL,
    'EG',
    'Others',
    'Robotic surgery',
    'Junk',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475645","content":"He is a student","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed El Lakkany',
    'Leko_barca',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018475207","content":"Line busy Text in whats up","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Serish Umar',
    'Sehrishmahmood18',
    NULL,
    'AE',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018475406","content":"RNR text in whats up","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'ОНКОЛОГ•ПРОКТОЛОГ•ЛЬВІВ',
    'Boikor',
    NULL,
    'UA',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018475416","content":"Called to Dr Answer and disconnected the call .DR responsed in whats up","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdelrahman Zaki Ali Mohammed',
    'Abdelrahmanraslan20',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018475547","content":"RNR text in whats up","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Viknesh Subramaniam',
    'Vickrg470',
    '+60172600499',
    'MY',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-175915101847586","content":"RNR text in whats up","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mustafa Omara',
    'Omaramustafa',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018475322","content":"Called to Dr Answer and disconnected the call .DR responsed in whats up","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mostafa Ezzat Abd Aldaym',
    'Sasazezo_17',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Warm',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018475689","content":"Dr respond in whats up regarding the fee for robotic surgery","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Mamdouh Elshawarby',
    'Ahmedelshawarby23',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018475206","content":"RNR text in whats up // Called to Dr Answer and disconnected the call text in whats up","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Roma Kurchyk',
    'Kurchyk69',
    NULL,
    'UA',
    'Others',
    'Robotic surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-175915101847580","content":"Called to Dr Answer and disconnected the call //Called to Dr Answer and disconnected the call text in whats up","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'واتس فقط ممنوع الاتصال',
    'Dr.muhammadfffathy',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-175915101847573","content":"Line busy Text in whats up //Line busy","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr Mohamed Yehya',
    'Dryahya1681979',
    NULL,
    'SA',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018475879","content":"RNR text in whats up // line busy","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Pedro HCS',
    'Pcaccozzi',
    NULL,
    'BR',
    'MD/MS/DNB',
    'Robotic surgery',
    'Warm',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018475811","content":"Dr text back in whats up Dr looking for robotic surgery ask regarding the fee // Text dr in whats up waiting for resposne","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Alexandre Borgheresi',
    'Alexandreborgheresi',
    NULL,
    'BR',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018475550","content":"Voice mail text in whats up // Voice mail","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohammed Al Borgi',
    'Mohammedalborgi',
    NULL,
    'MA',
    'Others',
    'Robotic surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-175915101847575","content":"Line busy Text in whats up // line busy","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Rayan Ali',
    'Rayanali43439',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018475551","content":"Tried to call the Dr but not reacheabel T // switch off","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Essam Atef Ahmed Raafat',
    'Drshabrawy29',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475291","content":"Whats app kiya//","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Saad',
    'F.medo',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Warm',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475491","content":"whats app msg done//","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Abd El Naser',
    'Ahmed_naserdrea3',
    NULL,
    'EG',
    'Others',
    'Robotic surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475743","content":"call back , whats app sent","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Islam Mahmoud Asery',
    'Eslam.asery86',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475915","content":"call back , whats app sent","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Israa Es-safar',
    'Essafarisraa',
    NULL,
    'MA',
    'Others',
    'Robotic surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475528","content":"call back , whats app sent","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ervand Kirakosyan',
    'Yervandkirakosyan001',
    '+37441655355',
    'AM',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475341","content":"call back , whats app sent","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Nirodha Abeywardhana',
    'Niroabey',
    '+94771926707',
    'LK',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475306","content":"call back , whats app sent","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sirojiddin Ziyevuddinovich Bariatriya Xirurg',
    'Esz070790',
    NULL,
    'UZ',
    'Others',
    'Robotic surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475923","content":"call back , whats app sent","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dev',
    'Devanraj.selvam',
    '+60172358056',
    'MY',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475761","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Talaat',
    'Mohamedzyada930',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101847546","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr. Raphael de Oliveira e Silva',
    'Rapha_tkd',
    NULL,
    'BR',
    'Others',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101847553","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Pereira Fo',
    'Dr.dilson10',
    NULL,
    'BR',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475678","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Yahya Zakaria',
    'Ya7ya.zakaria',
    NULL,
    'EG',
    'Others',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475466","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hosam AlamE''dien',
    'Dr_h_alamedien',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475225","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ghizlane El aabdouni',
    'Gabdouni95',
    NULL,
    'MA',
    'Others',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475586","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Thoufeek Sarjoon',
    'Sarjoon221',
    '+94775383221',
    'LK',
    'MBBS/ FMG',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475995","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Jeffrey siang',
    'Warrenlo',
    '+60123090125',
    'GB',
    'MBBS/ FMG',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475388","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Paulo Teixeira Jr.',
    'Paulotx',
    NULL,
    'BR',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475958","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Muhammed Salah Wereda',
    'M.wereda',
    NULL,
    'SA',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475975","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mahmoud Shaban',
    'Dr.sh3boooo2014',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475544","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Eslam Elkoumy',
    'Elkoumy7',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475754","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ayman Nabil',
    'Ayman_n_w',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475327","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdelmjid Khaddadi',
    'Abdelmjidkhaddadi723',
    NULL,
    'MA',
    'Others',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475530","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Mohy',
    'Doctorahmedmohy73',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018475971","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohammed Fteet',
    'Mohammedfteet',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018475872","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'شريف صبحى',
    'Sherifsobhy361',
    NULL,
    'EG',
    'AYUSH',
    'Robotic surgery',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018475963","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'ᎽᎯ ᏚᎷᎥᏁᎬ',
    'Shwshm73',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018475384","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Elhaj Hamid Radallah Adam',
    'Hradallah',
    NULL,
    'SD',
    'MBBS/ FMG',
    'Robotic surgery',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018475493","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sudhanshu Ranjan',
    'Ranjan.sudhanshu5',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Robotic surgery',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018475589","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Elsayed',
    'Elbohoty79',
    NULL,
    'AE',
    'MBBS/ FMG',
    'Robotic surgery',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018475842","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'André Luiz',
    'Elcoringa',
    NULL,
    'BR',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018475379","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Haitham Abdel Wahab',
    'Dr_haytham89',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018475701","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Zakaria El Hafi',
    'Zakielhafi',
    NULL,
    'MA',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018475315","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Rana Waheed',
    'Akaane88',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-175915101847591","content":"text on what","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Khaled Azam',
    'Dr.khaledazam2001',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475331","content":"Line Busy","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'DrAhmed Sabry',
    'Ahmedsabry369',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475292","content":"No whataap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Basma Ayman',
    'Basmaaymanfikry',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475773","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Raafat',
    'Dr.mohamedraafat34',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475845","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Reuben Abraham Thomas',
    'Reubencrm',
    '+60177721985',
    'MY',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475638","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed AbdAlla AbdElsalam',
    'Orthomaster',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475643","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Elseddik Mousa',
    'Memo3mosa',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475825","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohammed Bahaa',
    'Mohammed92002',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475359","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Peter Alfy',
    'Petersurgery',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-17591510184757","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Omar Alaa',
    'Omaralaa91',
    NULL,
    'EG',
    'Others',
    'Robotic surgery',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475884","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Omar Ahmed AbdElWahab Saleem Refaie',
    'Surgeon0339',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475923","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamad Fouad Elnagar',
    'Drmohamadfouad26',
    NULL,
    'EG',
    'Others',
    'Robotic surgery',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475413","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Kasun Wijesingha',
    'Kasunwijesingha1971',
    '+94778879303',
    'LK',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475308","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Georgejohn K Thomas George',
    'Georgejohn007',
    '+60193810652',
    'MY',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475623","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Hossam',
    'Moh2332007',
    NULL,
    'EG',
    'Others',
    'Robotic surgery',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475782","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Elghonemy',
    'Mohamed.alghonemy',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-175915101847563","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hossam Abdelaziz',
    'Semsemnhnh',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475763","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'SHERIF TONI',
    'Sheriftoni96',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476502","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Wilson Eustaquio',
    'Wilsoneustaquio',
    NULL,
    'BR',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476193","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Ben Mosa Elabady',
    'Am2961136',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476966","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Alla Khatim Awad',
    'Drallakhatim',
    NULL,
    'SD',
    'MBBS/ FMG',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476614","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mostafa Khattab',
    'Khattabmostafa1',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476577","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Walid Khalifa',
    'Walidkhalifa4',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476435","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'يوسف إبراهيم',
    'Ynasr1175',
    NULL,
    'EG',
    'Others',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476550","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'mohamed alabd',
    'Mohamedhamdy0680',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476172","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdelrahman Samir',
    'Coolb2002y',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476219","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Islam Abdelrhman',
    'Dr.islam_abdelrhman',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476315","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'د.محمد عبد الحكيم منصور',
    'Mo.surg10',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476970","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr Shanawaz alam',
    'Drshanawazalam00119',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476533","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mouad Nouri',
    'Mohamednouri2003',
    NULL,
    'MA',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476212","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ibrahem Issac Gaied',
    'Ibrahimishak9070',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476852","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);
