-- IBMP Leads Import - Batch 05
-- Records: 100
-- Generated: 2025-09-29T13:18:26.728Z

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Purushoth Kumaran',
    'Purushothkumaran',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018471547","content":"icna","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'jaimin gaudani',
    'Jaimin0305',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018471370","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mahmoud Hamoda',
    'Hamodamahmouda315',
    NULL,
    'SA',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018471882","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'global_business_marketing _services2024',
    'Halhably',
    '+97455549694',
    'QA',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018471776","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hasan AL-Sultan',
    'Alsoultanhassan',
    NULL,
    'YE',
    'Others',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018471536","content":"sent with int number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Njr Faz',
    'Fayznjr2001',
    NULL,
    'EG',
    'Others',
    'Interventional',
    'Warm',
    'Roshan',
    'IBMP',
    '[{"id":"note-175915101847142","content":"Call answer and disconnected the call text Dr in whats up Dr said no calling only he will talk in whats up Dr text in whats up and said he is intrested in fellowship in Cardiology hence details shared...","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mario Ashraf Farid',
    'Mashf71',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018471651","content":"No response and No whats up // line busy // rnr","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr Arbaj Ali Nawab',
    'Arbajnawab33',
    NULL,
    'US',
    'AYUSH',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018471228","content":"RNR text Dr in whats up dr responding in whats up // As per the qulification Dr is not eligible for the fellowship course.","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'irum',
    'Irumfaizan89',
    NULL,
    'PK',
    'Others',
    'Interventional',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018471136","content":"RNR Text Dr in whats up Dr responding in whats up // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'أسامه عبدالله الحبشي ابوعموري',
    'Asawerabdlah2019',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018471214","content":"switch off text dr in whats up // dr text in arabic and said dont know english // only he can speak arabic","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr.A_K_A_S_H_',
    'Akashguheriya5700',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Warm',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018471250","content":"RNR Text Dr in whats up // RNR // Dr said he is busy and ask to share with the deatils in whats up // Line busy // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr.Laxman Kundale',
    'Kundalelaxman',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018471231","content":"Bochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'mohamed abd almoiz jaafar',
    'Mhmdga3far',
    NULL,
    'EG',
    'Others',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018471916","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Elmilhe',
    'Czechali85',
    NULL,
    'LY',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018471762","content":"Bochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ravi Dixit',
    'Doctorravi93',
    NULL,
    'US',
    'AYUSH',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018471310","content":"BHMS He is looking for Next Months short terms course","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Bharat Kumar Gupta',
    'Bharatkumargupta517',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018471611","content":"Bochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Kelum Rajakaruna',
    'Kelumrajakarunamf',
    '+94774589278',
    'LK',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018471652","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Salman',
    'Drahmedsalman',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018471434","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Aziz Muratov',
    'Azizmuratov85',
    NULL,
    'UZ',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018471983","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'وليد خلف!9uysbyiiyy4yo Oo9ooyy9yyY',
    'Waleed.khalaf1980',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018471817","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdelrahman Elfeky',
    'Nanomohammed2776',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018471566","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hashan Chamalka Pathirana',
    'Chamalka.pathirana',
    '+94716937360',
    'LK',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018471377","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohammed Nabil Darweesh',
    'Mohammed_darweesh',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018471547","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Haytham Embaby',
    'Haytham_embaby',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018471685","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Tarek Salah',
    'Dr_tareksalah77',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018471624","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Walid Abdala',
    'Walidroshan',
    NULL,
    'SA',
    'Others',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018471514","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Amr El Shalakany',
    'Amrelshalakany27',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018471496","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ali Alqayem',
    'Dralqayemclinic',
    '+97339932828',
    'BH',
    'Others',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018471184","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Husseiny Nabil',
    'Dochnabil',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018471246","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Arsany Talaat Saber',
    'Arsanytalaat',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018471699","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mahmoud Mostafa',
    'Dr.mahmoudeldesoky',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018471162","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmad Mamdouh',
    'Ahmadreyad376',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018471562","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Amr Said',
    'Dragoo_18',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018471719","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Mahrous',
    'Mohammed.mahrous1993',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018471342","content":"no response in whats up // Line busy // LIne busy","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mahmoud Elsaudi',
    'Drmahmoudelghropy',
    NULL,
    'EG',
    'Others',
    'Robotic surgery',
    'Hot',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018471766","content":"Called to DR he ask to share the details in whats up said busy // RNR// DR replied in internatinol whts up","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mahmoud Fawzy',
    'Dr_mahmoud1994',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018471949","content":"RNR Text Dr in whats up / said he notintrested and disconnected the call","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Karem Shahin Zewar',
    'Karem_zewar',
    '30',
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018471984","content":"RNR Text Dr in whats up Dr text back in whats and said intrested in Robotic surgery and wants hands on training hence details shared . want hands on for just 30 days // line busy // RNR // saaid he wi...","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Amr Amin Ragab',
    'Amraminragab',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018471747","content":"RNR Text Dr in whats up // RNR // Dr answer and disconnected the cal","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr. João Pedro Pinheiro | Urologista',
    'Jpedropinheiro',
    NULL,
    'BR',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018471485","content":"RNR Text Dr in whats up // voice mail // voice mail // RNR // voice mail // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'moche',
    'Ramy.masoud',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Warm',
    'Roshan',
    'IBMP',
    '[{"id":"note-175915101847196","content":"Called to Dr said he is intrested in Robotic surgery but was busy ask to call back and share the details in whats up said he want Fee for hybrid 11 and 1 hence shared through whats up // No response /...","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Hossam',
    'Mohamedhossam303',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Warm',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018471857","content":"Called to Dr said he is busy and ask to share the details in whats up // RNR // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Shaban Tohamy',
    'Ahmedshaban37',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018471778","content":"switch off text in whats up // RNR // no response // RNR // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Tareq Mohamed',
    'Tare2kamel',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Warm',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018471716","content":"No response text Dr in whats up Dr is responding in whats up // Line busy // Line busy","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Aram Sedrakyan',
    'Aramsedrakyan',
    '+37491428144',
    'AM',
    'MD/MS/DNB',
    'Robotic surgery',
    'Warm',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018471171","content":"No response text Dr in whats up Dr text in whats up and said he is intrested in Robotic Surgery hence details shared through whats up // RNR // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ibrahim El Kashef',
    'Ibrahim.kashef',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018471546","content":"NO answer said he will consider the course in the future trying to reach Dr no answer // Dr said he cant afford now if we provide him in 300 usd he will enrol the course","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hamidou Guillaume Turpin',
    'Hguillaumeturpin23',
    NULL,
    'MA',
    'Others',
    'Robotic surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018471161","content":"No response text Dr in whats up // no response // RNR // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Wael Kamal',
    'Waelsalahent',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018471154","content":"Bochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdellah Bellefkih',
    'Abdellahbellefkih72',
    NULL,
    'MA',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018471234","content":"Not ANS","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Fesal',
    'Medoesam1995',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018471696","content":"Not ANS","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Medhat Mostafa',
    'Medhatmostafa69',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-175915101847152","content":"Not ANS","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'ALexander Shulyak',
    'Avshulyak',
    NULL,
    'UA',
    'Others',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018471842","content":"Not ANS","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Noureldeen Ashraf',
    'Nour_1949',
    NULL,
    'EG',
    'Others',
    'Robotic surgery',
    'Warm',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018471694","content":"Not ANS","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mahmoud Anwer',
    'Crazymody4',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018471453","content":"Bochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Yehia Sayed Elahl',
    'Yehiasayedelahl',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-175915101847126","content":"Bochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Randima Nanayakkara',
    'Prnanayakkara',
    '+94777845528',
    'LK',
    'MD/MS/DNB',
    'Robotic surgery',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018471181","content":"Bochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'George Nakhla',
    'George.william.nakhla12',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-175915101847196","content":"No what aap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohammed Abd El-Maugood',
    'Dr.mohammed.abdelmaugood',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Warm',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018471641","content":"Not ANS","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sayyd M. Khedr',
    'Sayedm760',
    NULL,
    'EG',
    'Others',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018471570","content":"Not ANS","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'ماجد نصرالله',
    'Drmagednasralla1982',
    NULL,
    'EG',
    'Others',
    'Robotic surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018471919","content":"Line busy text Dr in whats up // RNR // RNR // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdelhamid Zena',
    'Dr_abdelhamidabozena',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Warm',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018471915","content":"Dr answer and disconnected the call text Dr in whats up // RNR // RNR // Called to Dr ask to share the details of the course // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Mostafa',
    'Aboraia889',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018471503","content":"Not reacheabel text Dr in whtsup // rnr . DR respond in whats up and said due to Private causes he cant enrol this time","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Youssef Morkos',
    'Youbadie123',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Warm',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018472818","content":"Not reacheabel text Dr in whtsup . Dr respond in whats up for details // no Response // line busy // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    '𝑴𝑨𝑳𝑨',
    'Pandimalachellam2001',
    '+37491074565',
    'AM',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018472827","content":"RNR Text in whats up // Switch off // Not answering // Not answering // Not reacabl // Not reacabl","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hayati Samad',
    'Nyati284',
    '+60149662240',
    'MY',
    'Others',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018472248","content":"Not Answer","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Kithsiri Senanayake',
    'Kithsirijanakantha',
    NULL,
    'GB',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018472874","content":"Not connecting","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Abdelkhalek',
    'Drmabdelkhalek',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018472771","content":"No Answer","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ayman tharwat',
    'Draymantharwat',
    NULL,
    'EG',
    'Others',
    'Robotic surgery',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018472104","content":"She is speakin in arabic","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Mansour',
    'Dr.m.mansour713',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018472952","content":"No Answer connect on whataap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed. Kandil',
    'Mmkandil11',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018472565","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohie Madany',
    'Mohie25',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018472536","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mo Sabry',
    'Mosabry2012k',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018472607","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ali Elshiekh',
    'Alsudany17',
    NULL,
    'US',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018472566","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Osama Hegazy Abdelsalam',
    'Oshegazy2002',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018472795","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohammed Khalil',
    'Khalilmohammed35',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018472377","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed seliem',
    'Drahmedseliem',
    NULL,
    'EG',
    'Others',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101847224","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Chavan Dayal',
    'Puvechans',
    '+97334441465',
    'BH',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101847230","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Nada Sherif Diesel',
    'Nana.sherif.diesel',
    NULL,
    'EG',
    'Others',
    'Robotic surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018472520","content":"RNR and no whats up // line busy // line busy // line busy // line busy","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ваагн Ашугян',
    'Ashughyan',
    '+37491470442',
    'AM',
    'MBBS/ FMG',
    'Robotic surgery',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018472873","content":"Called to Dr said he is not understanding and ask to send a mail hence text in whats and mail // RNR // Dr is interested in robotic surgery in Urology","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Andranik Poghosyan',
    'Andpog.1989',
    '+37477039435',
    'AM',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018472382","content":"No response texrt in whats up // line busy // line busy / line busy / line busy","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Wajmah Alsayed',
    'Wajma.sayed',
    NULL,
    'EG',
    'Others',
    'Robotic surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018472203","content":"RNR Text in whats up rnr // / rnr / rnr","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'M.Khalil',
    'Dr_mohamed_khalil',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018472977","content":"RNR Text in whats up // no response // RNR // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Samir',
    'Drsamir444',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018472955","content":"Not answering brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Anvarbek Kurbanov',
    '2835949',
    NULL,
    'CN',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018472282","content":"Getting Busy brochure send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Sameeh',
    'Drmohamedhemida84',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Warm',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018472857","content":"Not answering brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sampath Gnanarathne',
    'Gnanarathnes',
    '+94777520088',
    'US',
    'MD/MS/DNB',
    'Robotic surgery',
    'Warm',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018472920","content":"Instrested details send 4200 usd","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sameh AbdulRahman',
    'Ssadek_md',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018472908","content":"Not answering brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Khaled Saeed',
    'Khaledzeama',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018472204","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Riad Warda',
    'Santafe28.12mm',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101847261","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Nada Tarek Abrahem',
    'Nadatarekibrahem',
    NULL,
    'EG',
    'Others',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101847297","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Surya Sharma',
    'Nicesuryaprakash',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Robotic surgery',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018472135","content":"after 4 months no reason he is having exams","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'د.ايهاب ناثان الفي زكي',
    'Dr.ehabnathanalfy',
    NULL,
    'DK',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018472788","content":"text in mail for whats up // RNR // rnr // rnr","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Batul fatima',
    'Lifeofbatool',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Fellowship Psyc',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018472178","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Madhuka Piyumal Dasanayake',
    'Madhuka1991sl',
    '+94711441467',
    'LK',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018472873","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed ElWaeer',
    'Ahmedalwaeer',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018472129","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Khairy Makled',
    'Drahmedmakled',
    NULL,
    'EG',
    'AYUSH',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101847250","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Kelum Rajakaruna',
    'Kelumrajakarunamf',
    '+94774589278',
    'LK',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018472541","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Aiswarya Suresh',
    'Aiswaryamsureesh',
    NULL,
    'India',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018472388","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Gyan kumar sonik',
    'Gyankumarverma120',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018472350","content":"Normal enquiry","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Gehane Yassa',
    'Geraro00623',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Echocardiograph',
    'Warm',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018472479","content":"RNR Text in whats up . Dr respond in whats up // rnr// rnr // rnr","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    '.....',
    'Ghadaalahdal',
    NULL,
    'US',
    'Others',
    'Interventional',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018472464","content":"RNR Text in whats up // line busy // line busy // line busy // line busy","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.472Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);
