-- IBMP Leads Import - Batch 09
-- Records: 100
-- Generated: 2025-09-29T13:18:26.732Z

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Kedar Dave',
    'Vandanapdave139',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474835","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'اسماء مفرح',
    'Asmaaaleasi',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474366","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hassa Iftikhar',
    'Hassabatool',
    NULL,
    'AE',
    'Others',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474716","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Moataz Abouelnour',
    'Motazaboelnour',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018474566","content":"call not answered , text kiya tha","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Rafael Fernandes da Conceição',
    'Rafaelfernandes_7',
    NULL,
    'BR',
    'Others',
    'Robotic Surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018474905","content":"evening call karo//whats napp did","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Shankar Gunarasa',
    'Drshanks72',
    '+60192226976',
    'MY',
    'Others',
    'Robotic Surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018474781","content":"malysia , answer kiya, whats app karo bola","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Roberto Avolio',
    'Roberto.avolio1',
    NULL,
    'BR',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018474185","content":"evening call karo//whats napp did","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Rodolfo Rodrigues Toniasso',
    'Rodolfo_toniasso',
    NULL,
    'BR',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018474220","content":"evening call karo//whats napp did","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Junhan Lai',
    'Junhan_lai',
    '+60162635267',
    'MY',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018474893","content":"malysia , answer kiya, whats app karo bola","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Sabry Elshennawy',
    'Drvelocity2010',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018474661","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdellah Nouri',
    'Nouriabdellah28',
    NULL,
    'MA',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018474922","content":"texted that cant talk","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Haritha Jayawardane',
    'Mharithadj55',
    '+94717668933',
    'LK',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018474598","content":"text kiya","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Kamal',
    'Ahmedkamal5555',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Hot',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018474754","content":"text kiya","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Kamel Bakry',
    'Drahmedkamelbakry',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic Surgery',
    'Warm',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018474487","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Nouran Tarek',
    'Nouratarek97',
    NULL,
    'EG',
    'Others',
    'Robotic Surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018474698","content":"Line Busy","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed El Mehdi Bensouda',
    'Mohamed.el.mehdi.bensouda',
    NULL,
    'MA',
    'MBBS/ FMG',
    'Robotic Surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018474627","content":"Not Ans","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Subhash',
    'Drspp92',
    '+60174525512',
    'MY',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018474648","content":"connect on whataap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Yasser Ali',
    'Yasser.okasha22',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018474147","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Nimantha Wijerathne',
    'Niwije',
    '+94777664558',
    'LK',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018474474","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Said Negm',
    'Said.negm',
    '+94777664558',
    'EG',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018474310","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sergey Hakobyan',
    'Seroge777',
    '+37491417941',
    'AM',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018474503","content":"Text on whataap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohammed Mahmoud',
    'Mohammedmahmoud244',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic Surgery',
    'Junk',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018474482","content":"He is not a Doctor","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'محمد عصام عبدالباسط شرعان',
    'Mohamadsharaan',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic Surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-175915101847490","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamad Baraa Amir Kassis',
    'Baraakassis',
    NULL,
    'SY',
    'Others',
    'Robotic Surgery',
    'Warm',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474774","content":"details sent on wtsapp on mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Raafat',
    'Dr_ahmedraafat',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474860","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Alan Patrick Bombonatto',
    'Bombonatto2',
    NULL,
    'BR',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474689","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed M. Ghorap',
    'M_ghorap',
    NULL,
    'EG',
    'Others',
    'Robotic Surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474118","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Michelli Daltro',
    'Midaltro',
    NULL,
    'BR',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474135","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Rawan Hajjar',
    'Rawanhajjar200',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic Surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474898","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Amro Elhoussieny',
    'Amroelhoussieny',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474711","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ismail Abougendy',
    'Iabogendy',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic Surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474853","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mostafa El Ayoubi',
    'Moselayoubi',
    NULL,
    'MA',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474425","content":"I am already registered for a laparoscopy course this year next year he will enroll","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Alexandre R. Sá | Gastrocirurgia | Recife & Olinda',
    'Alexandremedcg69',
    NULL,
    'BR',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474490","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hicham Assofi',
    'Assofi001',
    NULL,
    'MA',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018474949","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Gamal',
    'Prof_pepsi',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic Surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-17591510184743","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.474Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'AAhmed Tantawy',
    'Ahmedtantawy474',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475633","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Sheta',
    'Msheta464',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475925","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mostafa Mohamdy Elshazly',
    'Mostafalis2022',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475547","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'JP',
    'Jpcalheiros',
    NULL,
    'BR',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475774","content":"wtsapp msgs sent","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Maha Khalaf',
    'Maha.394027140',
    NULL,
    'EG',
    'Others',
    'Robotic Surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475367","content":"wtsapp msgs sent","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dahlia Moharam ElGohary',
    'Dalia.hussein',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic Surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475310","content":"wtsapp msgs sent","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr. Rahman Ghaffarzadekan Rabati',
    'Dr.rahman.ghaffarzadegan',
    NULL,
    'Uzbekistan',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Hot',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475895","content":"wtsapp msgs sent","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ashraf Al-HusAن٦٦زAL-Husar هوl-٦ ٦نHusنsن٦ن٦aini٦',
    'Ashrafka2',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475727","content":"no whats app please share mail","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Which Wine',
    'Drfelipe',
    NULL,
    'BR',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475429","content":"wtsapp msgs sent","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'maha',
    'Diany.maha',
    NULL,
    'MA',
    'Others',
    'Robotic Surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475876","content":"wtsapp msgs sent","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Khalid EL Mortaji',
    'Elmortajikhalid',
    NULL,
    'MA',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475847","content":"wtsapp msgs sent","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'ArthWill',
    'Abaharthur',
    NULL,
    'NL',
    'MBBS/ FMG',
    'Robotic Surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475677","content":"wtsapp msgs sent","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Abbas Elkhouli',
    'Aabaselkhouli',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475591","content":"wtsapp msgs sent","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Bam Thoracic',
    'Bam220522',
    NULL,
    'US',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475165","content":"connect on whataap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Alshawy',
    'Drahmedalshawy1',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-175915101847558","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Hăssăn Ǯtiă',
    'Ahmedhassan3tia',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475290","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Emad Mostafa',
    'Emad.most',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475941","content":"connect on what ap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Rim Mernissi',
    'Rim.mernissi17',
    NULL,
    'MA',
    'Others',
    'Robotic Surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475976","content":"call hang up","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Ben EL Ouafiq',
    'Ahmed.emsi',
    NULL,
    'US',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475691","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Esam Mohamed Rashad',
    '3samrashad',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic Surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475627","content":"Text on whataap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Ashraf Eweda',
    'Eweda558',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic Surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475457","content":"Text on whataap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Pedro Pinheiro',
    'Drpedropinheironeto',
    NULL,
    'US',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475771","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Zainul Ariffin Mohammad Alfi',
    'Zainulipin',
    '+60134148756',
    'MY',
    'MBBS/ FMG',
    'Robotic Surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475320","content":"Text on whataap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Salma Helmy',
    'Salmahelmy002',
    NULL,
    'EG',
    'Others',
    'Robotic Surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475505","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Houssam-Eddine Berri',
    'Hossamsum',
    NULL,
    'MA',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475348","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ігор Калій',
    'Kalii.ihor27',
    NULL,
    'UA',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475815","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Doc Mohammed Amine El Oualid',
    'Hard.amine',
    NULL,
    'MA',
    'Others',
    'Robotic Surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475139","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Lucas Tannus',
    'Lucfm_1',
    NULL,
    'BR',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475439","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'DrDhaneesh Karuppusamy',
    'Drdhaneeshk',
    '+37455415301',
    'AM',
    'MBBS/ FMG',
    'Robotic Surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475325","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sma Ali',
    'Najmhuda560',
    NULL,
    'US',
    'Others',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475186","content":"Not Connect","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'ايهم شهابي',
    'Ayhamshehabi639',
    NULL,
    'MA',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475240","content":"connect on what aap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hamed Gaber',
    'Hamedgaber31',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475451","content":"Not Connect","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Suvir Gupta',
    'Suviricha',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475434","content":"connect on what aap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'وفى أنفسكم أفلا تبصرون',
    'Fox054899',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475616","content":"connect on what aap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Satyam Singh',
    'Satyamgolu001',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018475219","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'elrashid eltayeb',
    'Elawadrashid',
    NULL,
    'US',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475686","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abhinav Pandey',
    'Abhinav.pandey2307',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475918","content":"today details sent","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdalsalam Algamal',
    'Abdo75gamal',
    NULL,
    'SA',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475668","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Bassam Sheryan',
    'Bassam.sheryan',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475302","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Naveen Kumar',
    'Drezhilarasi',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475568","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hemier Sarea',
    'Alsareeah',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475565","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'د.فاروق برمان',
    'Faroukabdul737',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475189","content":"Call Back after 1 year","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abuelwafa Mosad',
    'Uba57569',
    NULL,
    'EG',
    'Others',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475765","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Yahya Elssaman',
    'Ay996539',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475499","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Wafik El Gamil',
    'M.wafik2',
    NULL,
    'EG',
    'Others',
    'Interventional',
    'Warm',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475357","content":"call back , whats app sent","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Maftuna',
    'Maftuna1504',
    NULL,
    'UZ',
    'Others',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475439","content":"no whats app, call didnt connect","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'DrRavi Meshram',
    'Drravimeshram',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Follow Up',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018475210","content":"call cut kiya","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mostafa Youssef LOTFY KHALIF',
    'Mostafayosof356',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475163","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr. Zahraa General Surgeon',
    'Zahraa_futooh',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101847524","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Karen Julhakyan',
    'Kjulhakyan',
    '+37491406806',
    'AM',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475533","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Danusa Becker',
    'Danusabecker.db',
    NULL,
    'BR',
    'Others',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475303","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sujanthe Wickramasinghe',
    'Sujanthe',
    '+94772094500',
    'LK',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475150","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Rinat Gadoyev',
    'Rinatgadoyev',
    NULL,
    'UZ',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475938","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'kinji',
    'Kimsro86',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475121","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Rashad El Ghool',
    'Rashadelghool',
    NULL,
    'EG',
    'Others',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475756","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'محمد ابراهيم درويش',
    'Mdarwesh37',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475418","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Андрей Москаленко',
    'Prime108',
    NULL,
    'UA',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475731","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Kugadas Sutharshan',
    'Ksuthathshann',
    '+94773986156',
    'LK',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475539","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'DrHisham Ibrahim',
    'Drhisham55',
    NULL,
    'EG',
    'Others',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475484","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sharif Ahmad',
    'Sharifaalkarim',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475560","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Thri Mourthi',
    'Mourthi',
    '+60195747750',
    'MY',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475847","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ihab Ragab Alaqtash',
    'Cts.ihabragab',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475811","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'محمد طه موسي',
    'Temo_smsa88',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475918","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Евгений Ковеня',
    'Kovenajena',
    NULL,
    'UA',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475655","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Miracle Medhat',
    'Miraclemedhat420',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018475745","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.475Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);
