-- IBMP Leads Import - Batch 04
-- Records: 100
-- Generated: 2025-09-29T13:18:26.727Z

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'cha',
    'Cha3454',
    '+60143384549',
    'MY',
    'Others',
    'Critical care a',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018469209","content":"Not connect","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.469Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdl Ali',
    'Hafaineabdo',
    NULL,
    'MA',
    'Others',
    'Psychiatric ads',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018469773","content":"No Ans And No what aap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.469Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdulsalam Saif',
    'Abdsaif2030',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018469382","content":"RNR // RNR ( called Dr more then 5 times ) // RNR // RNR // Busy tone // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.469Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'dr Priyanka plr therapist',
    'Selfsoulascesion201',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-17591510184690","content":"RNR // RNR ( called Dr more then 5 times ) // RNR // RNR // RNR // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.469Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Rasika Samyak Kirat',
    'Rasikasamyakkirat555',
    '9765064666',
    'NP',
    'Others',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018469772","content":"RNR showing likely fraud // RNR showing likely fraud ( called Dr more then 5 times ) // RNR showing likely fraud // RNR showing likely fraud // likily fraud","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.469Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr.Aabha',
    'Voicingmybit.2020',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018469439","content":"Called to Dr said busy and ask to call back tomorrow again at 3 pm and ask to send the details in whats up hence shared the details // Voice mail // Called to Dr she is intrested in fellowship Psychia...","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.469Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'VIBHORE AWASTHY',
    'Awasthyvibhore',
    NULL,
    'US',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018470324","content":"Called to Dr he ask to share with the course which we provide in fellowship and was busy in hospital Dr text in whats to share the details for fellowship in Diabetology and Endocrinologydetails shared...","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Jihan Raafat Sourial',
    'Mandj75',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018470722","content":"RNR // RNR ( called Dr more then 5 times ) // RNR // RNR // RNR // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abhinav Yadav',
    'My8286296',
    NULL,
    'IN',
    'Others',
    'Psychiatric ads',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018470712","content":"switch off // Called to Dr said he is bmys and looking for the course said him he is eligibel for pgd course Dr ask to share the details in whats up // Dr answer and disconnected the call msg Dr in wh...","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr.Mst Mostary Zannath',
    'Drmstzannath',
    NULL,
    'Bangladesh',
    'Others',
    'head and neck o',
    'Warm',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470107","content":"details sent awaiting for dr response","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Parshuram Pawar',
    NULL,
    '9067850823',
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470195","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr. Aziza Tavakkalova',
    NULL,
    NULL,
    NULL,
    'MD/MS/DNB',
    'fetal echocardi',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018470568","content":"Number given by nikhil sir not reachabel // Line busy // Dr is asking for fetal echocardiography course // Line busy // dr is asking for fetal echocardiographyand said he will enrol later","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'NAERTERHTE1084231NERTYTRY',
    'Gwjglsog',
    NULL,
    'Madagascar',
    'Others',
    'General Medicine',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470672","content":"mail shared awaiting for response","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Suvonov Shoxrux Shuxratovich',
    'Shoxruxuzb99',
    NULL,
    'UZ',
    'MD/MS/DNB',
    'Cardiology ad',
    'Warm',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470185","content":"resharing the details int phone","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Kacem Bargach',
    'Kacem-bargach',
    NULL,
    'MA',
    'MD/MS/DNB',
    'Cardiology ad',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101847040","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Medicopolis Council',
    'Drmdsalmankhanwarsi',
    NULL,
    'IN',
    'AYUSH',
    'Cardiology ad',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470461","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mostafa Abdelghany',
    'Mostafa_maadi',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Cardiology ad',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470276","content":"mail sent awaiting for number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'أٌمنيه𓍢ִ໋͙֒✧',
    'Omniaabdelwahabb2003',
    NULL,
    'EG',
    'Others',
    'Cardiology ad',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470290","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Md akram',
    'Mdakramgd',
    NULL,
    'IN',
    'Others',
    'Cardiology ad',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470747","content":"mail sent","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Motea Jamil',
    'Jamil.motea',
    NULL,
    'DZ',
    'MD/MS/DNB',
    'Cardiology ad',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101847030","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'JATIN SONKAR',
    'Jatinsonkar48',
    NULL,
    'IN',
    'Others',
    'Critical care a',
    'Junk',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470329","content":"he said wrong number call hanguped","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'داود فضل',
    'Dawoud7202',
    NULL,
    'SD',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018470665","content":"Line busy no whats up // Line busy // not reachabel // line busy // Line busy","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Drasmaa Sakran',
    'Sofyhassan',
    NULL,
    'SA',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018470758","content":"Called to Dr said the voice is not clear and ask to text in whats up // RNR // LINE BUSY // not answering // not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Elenga Gift Owhondah',
    'Egoflex360',
    '+17863548221',
    'US',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018470952","content":"voice mail text Dr in whats up // Dr text in whats up said he is intrested in fellowship in Psychiatry but was having the doubt on the accredition which we are providing hence dealing by akshay bhiya...","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Melca Victoria Fernando',
    'Melcavicto',
    NULL,
    'GB',
    'Others',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-17591510184706","content":"RNR // RNR // Said not intrested for course","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Deize Farias',
    'Fariasdeize20',
    NULL,
    'BR',
    'Others',
    'Psychiatric ads',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018470939","content":"Not reacheabel no whats // RNR // RNR // RNR // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'اެنَـاެ اެݪـحِـاެڪَمہ َِ! َ',
    'Alzwqrysami',
    NULL,
    'US',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018470268","content":"RNR // Not reacheabel no whats // no response // no response // no response","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr Ritesh Kashyap',
    'Riteshk2004',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018470896","content":"no incoming services // no incoming services // no incoming services // no incoming services // no incoming services","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr Kiran | Gynaecologist | Fertility specialist',
    'Kiranbarhe715',
    NULL,
    'IN',
    'AYUSH',
    'Robotic Surgery',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018470326","content":"voice mail text Dr in whats up // Called to Dr he asked to call back after 1 hr // Dr is not eligibel for the course","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohammad Nahel Sorour',
    'Nahelnahel',
    '1021544424',
    'EG',
    'MD/MS/DNB',
    'Robotic Surgery',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018470757","content":"Line busy no whats up // line busy // line busy // line busy","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Deepika Verma',
    'Bdeepu.2603',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Reprodcutive me',
    'Follow Up',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018470535","content":"Switch off text Dr in whats up // Switch off // busy tone // Switch off // busy tone // busy tone","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'منى خليل',
    'Mona_m_khalil72',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Reprodcutive me',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470941","content":"Brochres send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Waseema Syed',
    'Waseema.syed',
    NULL,
    'US',
    'MBBS/ FMG',
    'Reprodcutive me',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-175915101847031","content":"brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Gopika I V',
    'Gopikaivtvm',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Reprodcutive me',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-175915101847037","content":"Brochres send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdelali Kallali',
    'Abdogyn84',
    NULL,
    'FI',
    'MBBS/ FMG',
    'Reprodcutive me',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470943","content":"Not Connecting","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mena Ekladios',
    'Mena1101987',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Reprodcutive me',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-175915101847092","content":"Brochres send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Renuka Goudoor',
    'Renukas12',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Reprodcutive me',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470126","content":"No Answer","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sunil Shaw',
    'Sunilshawcmc2007',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Reprodcutive me',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470475","content":"No Ans","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Shradha Vohra',
    'Shradha.vohra',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Reprodcutive me',
    'Hot',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470461","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dhruvi Nair',
    'Poladhruvi195',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Reprodcutive me',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470442","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Afreen Anwar',
    'Bismaahmed31',
    '7353729999',
    'IN',
    'MD/MS/DNB',
    'Reprodcutive me',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470881","content":"Call not connect","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Amel Albert',
    'Amelalbert93',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Reprodcutive me',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470496","content":"Not Ans","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'DR ASHISH SHARMA',
    'Dr.ashishsharma1136',
    NULL,
    'IN',
    'AYUSH',
    'Reprodcutive me',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470114","content":"Not Answer","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ashwin',
    'Ashwinmini008',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470586","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr Vijay Chauhan',
    'Chauhanvijay872',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470733","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Tony',
    'Antoniousrafaat91',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470641","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'د. نايل احمد سيد رضوان',
    'Drnayelradwan',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470703","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'AYAH J. A. ABUIYADA',
    'Ayah.j.a.abuiyada',
    NULL,
    'PS',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470259","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Tarek Dabash',
    'Tarekcardio',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470285","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Ali',
    'Sharaby85',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470398","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Salah Alhashmi',
    'Salahalhashme',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470271","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Kamal Alturki',
    'Abohashimkamal',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470418","content":"FORWARDED VOICE MAIL","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Karim Hatab',
    'Karim.hatab87',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470346","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Muhammad Wajahat t Jan',
    'Muhammadwajahatjan',
    NULL,
    'PK',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-175915101847039","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sumit choudhary',
    'Sumitchoudhary975462',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470708","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Kent Kho Khian',
    'Dr.kentkho',
    '+60127303779',
    'MY',
    'Others',
    'Interventional',
    'Warm',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470436","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Yogiraj Shillewad',
    'Yogeshwarshilewad',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-175915101847045","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'عبد الوهاب محمه كريب',
    'Krybbdalwhab359',
    NULL,
    'YE',
    'AYUSH',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470992","content":"Not connecting","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'José Eduardo',
    'Jellos66',
    NULL,
    'BR',
    'MBBS/ FMG',
    'Critical care a',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470747","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Awadbasheer Ali',
    'Dr.awadbasheer1',
    NULL,
    'SA',
    'MBBS/ FMG',
    'Critical care a',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470784","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mostafa Aladly',
    'Mostafaaladli915',
    NULL,
    'EG',
    'Others',
    'Critical care a',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470610","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Khawaja',
    'Drwajih29',
    NULL,
    'SA',
    'MBBS/ FMG',
    'Critical care a',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470492","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Kalai',
    'Kalatheran10',
    '+60125331284',
    'MY',
    'MD/MS/DNB',
    'Critical care a',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101847088","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'احمد عادل محمد زايد',
    'Ahmednemnem84',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Critical care a',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470339","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Mahmoud',
    'Medo16125578',
    NULL,
    'EG',
    'Others',
    'Critical care a',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470235","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Bishal Subedi',
    'Dr.bishalsubedi1',
    NULL,
    'NP',
    'MD/MS/DNB',
    'Critical care a',
    'Warm',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470336","content":"Connect on whataap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Masadul Sk',
    'Sksarip9083046',
    NULL,
    'US',
    'MBBS/ FMG',
    'Critical care a',
    'Junk',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470485","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr-Kaled Zimmo',
    'Drkaledzimmo',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Reproductive me',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470520","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dvya Patel',
    'Deepapatel5843',
    NULL,
    'IN',
    'Others',
    'Reproductive me',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470191","content":"he is not interested he is looking for his cousin","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'د.سلوى الغميري',
    'Dr.athwari',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Reproductive me',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470360","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'ياسر سيف هالل',
    'Ayasralzzy',
    NULL,
    'US',
    'MBBS/ FMG',
    'Reproductive me',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470168","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'MP Singh',
    'Worldpacificsportsfederation',
    NULL,
    'US',
    'MBBS/ FMG',
    'Reproductive me',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470318","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohammed Abd El Aziz',
    'Surzezo86',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470919","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Abdelmohsen shaban',
    'Mohsenroom',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470850","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Tigran Byuzandyan',
    'Byuzandyantigran',
    '+37498080704',
    'AM',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470138","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mher Mxitaryan',
    'Mher1731',
    '+37498303149',
    'AM',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470966","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'т.адхам',
    'Adhamjontoxtayev669',
    NULL,
    'US',
    'Others',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470971","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'أحمد حسين',
    'Ahmadhafez98',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470314","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdel Hamid Hussein Ezzat',
    'Hamidezzat',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470831","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abs',
    'Absamar',
    NULL,
    'BR',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470181","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Helmy Mohad',
    'Ahelmy1411',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470251","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ed MARSO',
    'Marso.amsts.ed',
    NULL,
    'MA',
    'Others',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470671","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Adel Elsharif',
    'Adelusa2002',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470568","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Anicet NSENGIYUMVA',
    'Nsenganicet8',
    '+25779645170',
    'MA',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470260","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Tawfik Zarif Boulos',
    'Abou_teffa',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470371","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Maher Zawawy',
    'Zwawymahz',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101847051","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hesham Mostafa',
    'Hmostafa67',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470657","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Сарвар Дехканов',
    'Sarvar-84',
    NULL,
    'UZ',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470370","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Yousry',
    'Ahmedyousry',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018470704","content":"rubeena mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ayman soliman',
    'Shakerayman7',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Warm',
    'Aslam',
    'IBMP',
    '[{"id":"note-17591510184700","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Bemen Besada',
    'Bemenadel211',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470708","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Wael Farouk',
    'Drwaelmoustafa',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470466","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'احمد نجيب عليوه',
    'Ah93eb',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470556","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Sobhy Mahmoud Husseiny',
    'Dr_mohamedsobhysurgery',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470360","content":"Connect on what aap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Шухрат Эшбеков',
    'Shukhrat9403',
    NULL,
    'UZ',
    'MD/MS/DNB',
    'Robotic surgery',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470218","content":"Brochure send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Мухаммад Али Каршибоевич',
    'Rabbimovm2003',
    NULL,
    'UZ',
    'Others',
    'Robotic surgery',
    'Warm',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470394","content":"Bochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Azam',
    'Ahmed_basha_3zam',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018470277","content":"Bochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.470Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr YAAKOUBI Mohammed',
    'Yaakoubimohammed06',
    NULL,
    'MA',
    'MD/MS/DNB',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018471225","content":"Bochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Anjana De Silva',
    'Anjana_desilva',
    '+94715425070',
    'LK',
    'MBBS/ FMG',
    'Robotic surgery',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018471368","content":"Bochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ijaz UL Haq Muhammadi',
    'Ijazulhaqbjr007',
    NULL,
    'PK',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018471151","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.471Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);
