-- IBMP Leads Import - Batch 01
-- Records: 100
-- Generated: 2025-09-29T13:18:26.701Z

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdullah Emad',
    'Abdullahemad028',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Fellowship Psyc',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018449873","content":"details sent on wtsapp will close soon","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.449Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abobakr Abdalah',
    'Ab3950436',
    NULL,
    'US',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018456682","content":"Dr answer and disconneted the call text in whats up","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.456Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Anoop vithayathil',
    'Anoopjaine4sik',
    NULL,
    'GB',
    'Others',
    'Psychiatric ads',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018456951","content":"Not connect","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.456Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    '𝙰𝙽𝚄𝚁𝙰𝙳𝙷𝙰',
    'Anuradhasngh815',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Fellowship Psyc',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018456844","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.456Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Arshad ali',
    'Arshadalifrnd',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018456224","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.456Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Aruna Shobha',
    'It',
    NULL,
    'IN',
    'Others',
    'Fellowship Psyc',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018456880","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.456Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Baidyanath Ghosh Dastidar',
    'Truegood001',
    NULL,
    'GB',
    'MD/MS/DNB',
    'Fellowship Psyc',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018456824","content":"RNR // RNR ( called Dr more then 5 times ) // line busy","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.456Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Belghit Elh',
    'Belghait.elhajjaj',
    NULL,
    'MA',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018456556","content":"dce","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.456Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Bibek Agarwal',
    'Bibek_ag',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018456390","content":"No Answer","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.456Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Boushikhi Fouad',
    'Abduallali44',
    NULL,
    'MO',
    'MBBS/ FMG',
    'Fellowship Psyc',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018456459","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.456Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Chaimae Kasmi',
    'Ckasmi70',
    NULL,
    'MA',
    'Others',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018456704","content":"Call disconectiong","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.456Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dares Ahmed Shams Eldin',
    'Www.d.daresaldee',
    NULL,
    'YE',
    'Others',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018456490","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.456Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dipendra KC',
    'Kcdipen007',
    NULL,
    'NP',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018456981","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.456Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr Santosh Shetty',
    'Dr.santosh111964',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018456545","content":"No incoiming Call","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.456Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr Syed Arif',
    'Dr Syed Arif',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018456359","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.456Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr.Ambedkar kumar Yadav',
    'Yadavambedkarkumar',
    NULL,
    'NP',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018456845","content":"-","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.456Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hemant Gupta',
    'Hemantgupta04',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Fellowship Psyc',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018459648","content":"He will call you","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.459Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'ismail Ismail',
    'Dr.ismailkamalismail',
    NULL,
    'DE',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018459462","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.459Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Jitendra Dutta',
    'Dr.dutta051284',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018459563","content":"Not connect","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.459Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Kerolus Kamel',
    'Kerolusk',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018459441","content":"-","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.459Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Khaled Aly',
    'Adreno82',
    NULL,
    'EG',
    'Others',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018459849","content":"Not Ans","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.459Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mahmoud Elazouny',
    'Dr.azounycardio',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018459595","content":"Not Ready for admisson","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.459Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mahmoud Maher',
    'Dr.mahmoudmaher1',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Fellowship Psyc',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018459150","content":"-","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.459Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Majeed Ansari',
    'Majeed3699',
    NULL,
    'US',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018459109","content":"Dr answered and discconnected the call // RNR ( called Dr more then 5 times ) // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.459Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Malla Phanindra',
    'Mallaphanindr5a',
    '9494694015',
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018459536","content":"Brochures send call back on 06 Sep","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.459Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Manoj Kumar',
    'Manojrazdan899990',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018459960","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.459Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mansi Agarwal',
    'Mansiagarwal185',
    NULL,
    'IN',
    'Others',
    'Fellowship Psyc',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018459233","content":"-","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.459Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mansoorali Kappachali',
    'Mansooralipulmo',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018459349","content":"switch off","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.459Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Marina Medhat Milad',
    'Marina_mm96',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018459588","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.459Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mariya-Rose-John-kannampilly',
    'Rosemariya803',
    NULL,
    'US',
    'Others',
    'Fellowship Psyc',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018459222","content":"RNR // RNR ( called Dr more then 5 times ) // rnr","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.459Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mayaank Gupta',
    'Mayankzzzzz',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018459172","content":"Not Ans","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.459Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mimita Mimita',
    'Lamiaa52',
    NULL,
    'MO',
    'MBBS/ FMG',
    'Fellowship Psyc',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018459929","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.459Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Gaballah',
    'Maagaballah',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018459761","content":"RNR // RNR ( called Dr more then 5 times ) // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.459Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Merekab',
    'Mohamedmerekab',
    NULL,
    'SA',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-175915101845951","content":"Line busy // RNR ( called Dr more then 5 times ) // line busy","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.459Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohammad Moustafa',
    'Petrogulfgroup',
    NULL,
    'EG',
    'Others',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018459372","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.459Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohammed Barhmi',
    'Drbarhmi',
    NULL,
    'US',
    'Others',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018459138","content":"brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.459Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohammed Khalid Saeed Saleh',
    'Mk5159861',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018459435","content":"RNR // RNR ( called Dr more then 5 times ) // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.459Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohy Ganab',
    'Mohyganab',
    NULL,
    'US',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018459113","content":"connect on whataap brcohures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.459Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Omar A. Baselm',
    'Obaselm53',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018459555","content":"He is student of MBBS 3 years","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.459Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Osama Al-aqel',
    'Osamaalaqel2',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018459855","content":"No connect","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.459Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Pallav dube',
    'Pallavdube09',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018459287","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.459Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Prabhu Sitham',
    'Psycapconsultancy',
    NULL,
    'MY',
    'Others',
    'Fellowship Psyc',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018459484","content":"Mail drop for Dr","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.459Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Pragati sherchan',
    'Pragati.sherchan',
    NULL,
    'SN',
    'MD/MS/DNB',
    'Fellowship Psyc',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018460259","content":"voice mail // voice mail ( called Dr more then 5 times ) // voice mail","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Raju Basnet',
    'Rajubasnet2052',
    NULL,
    'NP',
    'Others',
    'Fellowship Psyc',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018460932","content":"Said not intrested in whats up","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ramy b2b',
    'Dr.ramymagdysh',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018460888","content":"RNR // RNR ( called Dr more then 5 times ) // LINE BUSY","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Rinji',
    'Rinjiviswam',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Fellowship Psyc',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018460264","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ritendra Talapatra',
    'Rit.5mar',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018460754","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Rohit Kapoor',
    'Rohit_kapoor_rohit',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Hot',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018460216","content":"Called to Dr asked to Call back again after 6 pm // Dr text in whaatsup said will enrol details shared in whats up // Wating for Dr response as he said he will going to enrol for 2 members // said he...","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Roshan Khadka',
    'Drroshankhadka',
    NULL,
    'NP',
    'MD/MS/DNB',
    'critical care',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018460631","content":"Brochures send He is MD 30 years of Exp","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Roshan Kumar Jha',
    'Dr.rkjha',
    NULL,
    'NP',
    'MD/MS/DNB',
    'Interventional',
    'Enrolled',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018460680","content":"asked for references","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'S Shrikanth',
    'Sudarshanshridas',
    NULL,
    'IN',
    'Others',
    'Fellowship Psyc',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018460783","content":"RNR // RNR ( called Dr more then 5 times ) // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Samanthira',
    'Dhevisamanth',
    NULL,
    'IN',
    'Others',
    'Psychiatric ads',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018460311","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Samiera Ibrahim Hassn Abzid',
    'Samiera61',
    NULL,
    'US',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018460569","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sara Abo Daif',
    'Saramohamed.s2000',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018460825","content":"Line busy // RNR ( called Dr more then 5 times ) // line busy","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Siraj Ahamad',
    'Drsiraj0017',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018460174","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Uthumalebbe Sarafdeen',
    'Sarafdeenul',
    '+94773418234',
    'lk',
    'MBBS/ FMG',
    'Fellowship Psyc',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018460441","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'VARRUCHI JAISWAL',
    'Varruchij',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Fellowship Psyc',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101846091","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Waleed Abady',
    'Walabady',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Fellowship Psyc',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018460390","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Zouhair Issouani',
    'Zouhairissouani',
    NULL,
    'MO',
    'Others',
    'Fellowship Psyc',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018460764","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Маюран Понраса',
    'Pmauran8787',
    '+94750775122',
    'LK',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018460592","content":"RNR // Line busy ( called Dr more then 5 times ) // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'حسين DR. SK HUSSAIN VALI',
    'Shaikhussainvali467',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Fellowship Psyc',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018460898","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'د.عبدالسلام أحمد العقلاني',
    'A10313207',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018460401","content":"Not valid No","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'طاهرصالح محرم',
    'Tahersaleh31',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018460656","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'عارف الشعباني',
    'Alshabaniaref',
    NULL,
    'YE',
    'Others',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018460513","content":"RNR // RNR ( called Dr more then 5 times ) // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'علي حميد',
    'Alialhabashi13',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018460996","content":"RNR // RNR ( called Dr more then 5 times ) // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Taher Ali',
    'D.taheralali',
    NULL,
    'CD',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018460545","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dipin Mijar',
    'Dipinmijar',
    NULL,
    'NP',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018460727","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'N.Sheik Mohamed Thansil',
    'Thansilcardio',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018460540","content":"after 7 months he is busy with his internship","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr Srikanth Nayar',
    'Drsrikanthcardio',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018460722","content":"fellowship course asking in 80 k or 90 k","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr. Anas El Kholty',
    'Elkholty.anas',
    '+79881760746',
    'RU',
    'Others',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018460995","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'JagdishChandra',
    'Drjagdishchandramd',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018460140","content":"out of net cov area","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'صالح عامر',
    'Dr_salehamer',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018460641","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Kapil Suryawanshi',
    'Sdkapil143',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018460593","content":"not connecting the call","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Nashmi sadeq abdu mohammed',
    'Nashmialshraay',
    NULL,
    'YE',
    'Others',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018460432","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Nalin Perera',
    'Wnalinperera2',
    '+94714352912',
    'LK',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018460286","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.460Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Moula Bux Soomro',
    'Moulasoomro',
    NULL,
    'US',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018461770","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Issam Atidi',
    'Issamatidi3',
    NULL,
    'MA',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018461247","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ali Awad Habtoor',
    'Aliawadhabtoor618',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018461385","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Waheeb Dawass',
    'Dawasswaheeb',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018461838","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ali Mujalli',
    'Alimujalli',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018461607","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Razi Ahamed',
    'Razi.ahamed9',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018461744","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ariyaratnam Harigajan',
    'Drharigajan',
    '+94777573306',
    'LK',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018461294","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohammed Abdullah Ghaleb',
    'Mohamdrox',
    NULL,
    'YE',
    'Others',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018461938","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Haless Kamal',
    'Med.kamalhaless',
    '+33605897596',
    'FR',
    'Others',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018461465","content":"Not coneecting","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Meriam Amri',
    'Meriam.amri',
    NULL,
    'MA',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018461829","content":"Brochures Send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Javid',
    'Javid211',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018461219","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Olga Gamal',
    'Olga734151449',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018461104","content":"Not connecting","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sameer',
    'Randomtech195',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018461437","content":"He is preparing for FMG exam and brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Rhitik Katre',
    'Rhitikktre141',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018461175","content":"Brochures send He is busy","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ank',
    'Itsankur26',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018461264","content":"Not connecting","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Naresh',
    'Drnareshsen1',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018461268","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Islam Abdelfatah',
    'Drislamaboelenin',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018461963","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Uchiha Clan',
    'Gmanouar',
    NULL,
    'US',
    'Others',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018461367","content":"not connecting","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Zekri salmane',
    'Salmane.zekri1',
    NULL,
    'MA',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018461786","content":"not connecting","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hafssa Fiak',
    'Hafssafiak',
    NULL,
    'MA',
    'Others',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018461355","content":"brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Elsayed Abdelkder',
    'Abdelkadermohamed598',
    NULL,
    'US',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018461701","content":"brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'محمدعلي عبدالله حسين زيد',
    'Mohammedaliahmedzaid',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018461509","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mirjalol Omonov',
    'Mirjalolomonov971',
    NULL,
    'UZ',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018461825","content":"Interested details send call me at Sep 8 next week","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hossam Zahra',
    'Hossam.zahra1980',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018461184","content":"Line Busy Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Alhassan Alzandani',
    'Alhassnf',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018461652","content":"brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);
