-- IBMP Leads Import - Batch 11
-- Records: 100
-- Generated: 2025-09-29T13:18:26.734Z

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Gamal',
    'Dr.mohgamal',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101847622","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdelrahman El Malky',
    'Obegyna',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476769","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mazen Araby',
    'Arabymazen60',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476239","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Rachid Taoufiq',
    'Drtaoufiq',
    NULL,
    'MA',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476378","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Heba Ahmed',
    'Hebahmed531',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476427","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Omar Khaled Gad',
    'Khalef20',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476335","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Francesco Ferri',
    'Fraferri66',
    '+39335821473',
    'IT',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476664","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'abdessalam elmoussati',
    'Elmosati.abdessalam',
    NULL,
    'MA',
    'Others',
    'Robotic surgery',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476341","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohcine Azime',
    'Mohcine.amine.g1',
    NULL,
    'US',
    'Others',
    'Robotic surgery',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476103","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr. Demian | General Surgeon in Dubai',
    'Drdemyanpetrov',
    NULL,
    'AE',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476831","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Humera Bint Raees',
    'Drhumera_raees',
    NULL,
    'AE',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476241","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mariam Waguih',
    'Dr_m_guirguis',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-175915101847696","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Gor Melikyan',
    'Doc.gor.melikyan',
    '+37498778887',
    'AM',
    'MBBS/ FMG',
    'Robotic surgery',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476123","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Ismail',
    'Drmiseleem',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Robotic surgery',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476372","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Karim Mounaouir',
    'Karim.mounaouir',
    NULL,
    'MA',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476305","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ilyosbek',
    'Haydarovilyosbek1',
    NULL,
    'UZ',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476502","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr.Hiral Yadav',
    'Hiralyadav636',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476123","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sharath Shanmugam',
    'Sharathshan8',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476611","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr.Rajan Rajput',
    'Drrajanrajput8418',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476537","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Azahruddin Khan',
    'Azharuddinkhn2',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476498","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Minu-Zyd',
    'Minhazaid16',
    '+94755788961',
    'LK',
    'AYUSH',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476605","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr.Gautam Gupta',
    'Gautamgupta2896',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476249","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ashraf',
    'Ashraf.yassa',
    NULL,
    'EG',
    'Others',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476668","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Riya',
    '8740riya',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-175915101847687","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hussein Ahmed',
    'Drbamussali',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476239","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'PURU MADAN',
    'Purumadan',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476343","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Raghul Rock Star',
    'Raghulrockstar077',
    NULL,
    'US',
    'Others',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476639","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Paramu',
    'Paramuparameshwari290',
    NULL,
    'US',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476553","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Iqbal Khan Dr',
    'Drmikhan512',
    NULL,
    'US',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476472","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'N. lokeshkumar',
    'Neelakandan531970',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476173","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'عبدالتواب طحاوى',
    'Abdeltawabtahawy',
    NULL,
    'EG',
    'Others',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-175915101847647","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Darshan Nakum',
    'Darshannakum1704',
    NULL,
    'US',
    'AYUSH',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476406","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Othman Yahya',
    'Ousmanyahya1997',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476996","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Vishal Kesarwani',
    'Vishal.iitr.ar',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101847659","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr Karthik',
    'Sadusanketh89',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476799","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Salah',
    'Ahmedsalahdr',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476308","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'سامي الماس',
    'Ibnalmass17',
    NULL,
    'YE',
    'Others',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476344","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ibrahim Sabri',
    'Dr.sabri55',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476606","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hana Ahmed',
    'Abbud45',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476863","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mousad Mohamed',
    'Assasa151078',
    '+96565621070',
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476111","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'DS Patil',
    'Sunnybvanarse',
    NULL,
    'US',
    'AYUSH',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476799","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Shrouq Magdy',
    'Dr.shroukmagdy',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476526","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Youssef Ayoub',
    'Youssefayoub321',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476590","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    '𝓗𝓪𝓻𝓲𝓱𝓪𝓻𝓪 𝓢𝓾𝓭𝓱𝓪𝓷',
    'Harisudhan070602',
    NULL,
    'UZ',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476198","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Gulibonu Sadillayeva',
    'Gulibonu3012',
    NULL,
    'UZ',
    'Others',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476375","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'lissom yette Dieudonne',
    'Somyede',
    NULL,
    'GB',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476773","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sohil Ansari',
    'Mosohilsohil52',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476512","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'ठा. एच एस तरकर',
    'Hemanthakur9927',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476293","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Kerolos Ayman',
    'Kerolos.ayman',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476883","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Adel Abo Elfotouh',
    'Doctoradel4',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476827","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Arzikul Odilov',
    'Arzikulodilov',
    NULL,
    'US',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476492","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hasitha Kumara',
    'Ugshasitha',
    '+94714414026',
    'LK',
    'Others',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476485","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'MennatAlla Ehab',
    'Menatallaehab',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476271","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr.Syed',
    'Sulthanboss.ss',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476887","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'عبد المجيد البشري',
    'Hefdhallahalisaleh',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476157","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Suman Thapaliya',
    'Thapaliya_s',
    NULL,
    'NP',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101847617","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Yahya Alsersgi',
    'Yalseragi',
    '+12367882155',
    'CA',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476861","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Thanh Son',
    'Thanhsonjk98',
    '+84344799900',
    'VN',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101847642","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'محمد عطية أحمد',
    'Tytmhmd595',
    NULL,
    'EG',
    'Others',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476846","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr Rajesh Rajeev',
    'Aiimsneurosurgery17',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476591","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'pushpendra thakur',
    'Pushpendrasingh4368',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476923","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Adel Adham',
    'Adeladham01116452263',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476548","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'DR. NIKHIL JAIN',
    'Nikjainnj011',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476203","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Khawla Alshara''abi',
    'Khawla_alsharaabi44',
    NULL,
    'YE',
    'Others',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476957","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'sujata bhosale',
    'Sujatasm9',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-175915101847646","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Aastha Palikhe',
    'Aasthapalikhe',
    NULL,
    'NP',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476274","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Muhammad Atif Shahzad',
    'Muhammadatifshahzad1',
    NULL,
    'AE',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476876","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dranil kumar Soni',
    'Dranilsoni135',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-175915101847660","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'ابراهيم علي',
    'Al5630792',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476145","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abhishek Pateel',
    'Vimijain90',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476473","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Saquib Ali',
    'Saquibdr876',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476291","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Elshahat',
    'Mohamed.tekoo25',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-175915101847695","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Onkar Banne',
    'Bannya7101',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476285","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdralrahman Eltaher',
    'Neeel5536',
    NULL,
    'SD',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476324","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Panem Surendra',
    'Panemjuhisuren',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476355","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Saed Atawneh',
    'Saedata2004',
    NULL,
    'EG',
    'Others',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476992","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'مـحمـد آلحربيـﮯ',
    'Alharbiy2007',
    NULL,
    'US',
    'Others',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476916","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'nguyễn quốc việt',
    'Nqviet.hth',
    '+84378475122',
    'VN',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476449","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Rahul Dev',
    'Rahuldevraghuram',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476208","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Emara',
    'Emaraa866',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476233","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Karthik',
    'Thute.karthik97',
    '+97470231396',
    'QA',
    'Others',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476291","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Om Prakash Shah',
    'Opshahin',
    NULL,
    'NP',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476812","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abhi Thakur',
    'Abhisavita6394',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476464","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    '𝑨𝒃𝒅𝒖𝒌𝒂𝒓𝒊𝒎𝒐𝒗 𝑱𝒂𝒗𝒍𝒐𝒏 𝑺𝒉𝒆𝒓𝒛𝒐𝒅',
    'Abdukarimovjavlon368',
    NULL,
    'UZ',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476386","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Aman Saifi',
    'Amansaifi5656',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476977","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Gufran Khan',
    'Drgufrankhan',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476133","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Yamash',
    'Mohannadyemen15',
    NULL,
    'US',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-175915101847680","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Khaled Fadel',
    'Khaled81976.kf',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-175915101847620","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'தருண்',
    'Boogeyman2705',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476772","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Tuba Rahman',
    'Trehman2410',
    NULL,
    'US',
    'Others',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476362","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Pinku Rajpoot',
    'Rajpootpinku2001',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476953","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sanjay SG',
    'Sanjaysg940',
    NULL,
    'US',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476525","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Trí Phạm',
    'Quangtri3003',
    '+84979984320',
    'VN',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476325","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Qaher Aada',
    'Dy2020yd',
    '771089866',
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476275","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohammed AlGamra',
    'Moqhalgamra',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476282","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Malaz Ibrahim',
    'Loza.22001166',
    NULL,
    'SD',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476677","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mahmoud ibrahim',
    'Dr.mahmoudebrahem',
    NULL,
    'SA',
    'Others',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476802","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ibrahim Abdelsalam Sayed',
    'Dr_ibrahim333',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476963","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdelmajid Bouzerda',
    'Abdelmaji73',
    NULL,
    'MA',
    'Others',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476235","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'محمد احمد محمد عبد الجبار',
    'Wasly1233',
    NULL,
    'YE',
    'Others',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476712","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);
