-- IBMP Leads Import - Batch 02
-- Records: 100
-- Generated: 2025-09-29T13:18:26.725Z

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Navdeep Sharma',
    'Navdeepsharma1985',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Warm',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018461489","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Veena Rj',
    'Veenarj28smarty',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018461444","content":"Brochures send she is looking for 50,000/ course","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hương Lan',
    'Huonglanbt1306',
    '+84963000732',
    'VN',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018461789","content":"mail drop from nakshtra phone","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'RABI RIMAL',
    'Std.rabiprasadrimal',
    NULL,
    'NP',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018461773","content":"Not Ans","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hoàng Phú Quý',
    'Abteolu',
    '+84354669398',
    'VN',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018461774","content":"not connecting","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Saeed',
    'As26400567',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018461532","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr Rajeeve Kumar Rajput',
    'Rajeevekumar64',
    NULL,
    'US',
    'Others',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-175915101846162","content":"Call back request","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.461Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Amina Elhakeem',
    'A_elhakeem100160',
    NULL,
    'EG',
    'Others',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018462222","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.462Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Aashaq Hussain Khandy',
    'Aashaqhussain2011',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018462804","content":"Dr answered and disconnected the call // Dr answered and disconnected the call speaking other language // busy tone","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.462Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hassan Saady',
    'Drhassansadi',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018462527","content":"RNR // RNR ( called Dr more then 5 times ) // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.462Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamud Shire',
    'Maxamudcabdiqadir0',
    NULL,
    'SD',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018462222","content":"SWITCH OFF // SWITCH OFF ( called Dr more then 5 times ) // SWITCH OFF //RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.462Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Phạm Quốc Bằng',
    'Pqbangkg',
    '+84945770009',
    'VN',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018462179","content":"RNR // RNR ( called Dr more then 5 times ) // RNR // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.462Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'محمد احمد ناصر',
    'Mman731731',
    NULL,
    'YE',
    'Others',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018462597","content":"RNR // RNR ( called Dr more then 5 times ) // RNR // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.462Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'عبدالكريم الحماطي',
    'Alhamty2021',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018462396","content":"RNR // RNR ( called Dr more then 5 times ) // RNR // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.462Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dahmane Wissame',
    'Wis.shady',
    NULL,
    'MA',
    'Others',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018462815","content":"RNR // Voice mail ( called Dr more then 5 times ) // Voice mail // Voice mail","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.462Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahlam Mohammed',
    'Ahlamalghaili1',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018462683","content":"Busy tone // Busy tone ( called Dr more then 5 times ) // Busy tone // Busy tone","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.462Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'محمد حسن نجاد',
    'Nagad3322',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018462460","content":"Line busy // Line busy ( called Dr more then 5 times ) // Line busy // Line busy // Line busy // Line busy","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.462Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Shoxruxbek Axmadaliyev|MDInterventional Arrhythmol',
    'Akhmadalievshokhrukh04',
    NULL,
    'UZ',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018462489","content":"RNR // RNR ( called Dr more then 5 times ) // RNR // RNR // RNR // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.462Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'وسيم مجلي مجلي',
    'Waseemmijali',
    NULL,
    'YE',
    'Others',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018462271","content":"Call answered and no response // RNR ( called Dr more then 5 times ) // RNR // RNR // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.462Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'د.عبدالرحمن الحاذق',
    'Alhadhqbdalrhmn4',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-175915101846231","content":"RNR // RNR ( called Dr more then 5 times ) // RNR // RNR // RNR // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.462Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sundarapal Prasadarao Dr.',
    'Drpalprasad.sundara',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018462555","content":"No response // Call answer and disconnected the call ( called Dr more then 5 times ) // Said not intrested in whats up","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.462Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Bikramaditya Deb',
    'Bikramadityadeb',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-175915101846297","content":"Not reachabel // RNR ( called Dr more then 5 times ) // Busy tone // Busy tone // Busy tone // Busy tone","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.462Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohsin mustafa',
    'Mohsin.azad28',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018462849","content":"Busy tone // said already he is middel of a course once it ends in month of november he will come back for the course","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.462Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hundi Hundi',
    'Sanjaynepa',
    '9843270598',
    'NP',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018462470","content":"Line busy // Line busy ( called Dr more then 5 times ) // Line busy // Line busy // Line busy // likely fraud // likely fraud","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.462Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Saheb Jayswal',
    'Skj207',
    NULL,
    'NP',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018462479","content":"said condition in there county is not good will plan later on","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.462Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sanjay Singh',
    'Brach4sanjay',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018462157","content":"-","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.462Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Alaa Galal Essa',
    'Alaaessa10',
    NULL,
    'US',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018463822","content":"Line busy // Line busy ( called Dr more then 5 times ) // No response // RNR // Dr answer and disconnected the call","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Bushra Aqlan',
    'Bishokhaled1999',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018463965","content":"-","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'DR.SOFYAN',
    'Riyazsufyan9',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018463418","content":"-","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Gopal Suwal',
    'Gopalsuwal',
    NULL,
    'NP',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018463786","content":"Said he will check later as he is from np he will enrol later","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Duc Sy Le',
    'Leducsy2002',
    NULL,
    'CN',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018463570","content":"-","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Fikri Saad',
    'Dr.fikrisalem',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018463431","content":"RNR // RNR ( called Dr more then 5 times ) // RNR // RNR // Busy tone // RNR // DR answer and disconnected the call","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    '🅢🅘🅓',
    'Siddharthgumber2199',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018463389","content":"RNR // RNR ( called Dr more then 5 times ) // RNR // RNR // RNR // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'فارس رضوان',
    'Alrjhlasalm',
    NULL,
    'CA',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018463950","content":"RNR // RNR ( called Dr more then 5 times ) // Line busy // RNR // RNR // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ronak Modi',
    'Ronak_smartmodi39',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018463891","content":"-","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mariam Hassan',
    'Mariamadar19',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018463993","content":"-","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Naushad Akhtar',
    'Naushad000786',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-175915101846331","content":"Voice mail // Voice mail ( called Dr more then 5 times ) // Dr is intrested in Fellowship in Interventional Cardiology want fully online amount said 2500 usd having isuue in fees // Having issue in fe...","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hassan Aboellil',
    'Aboellil2040',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018463111","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Trần Đình Tuyên',
    'Tuyendhy1993',
    '+84962886689',
    'VN',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018463581","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Zakaria Wakrim',
    'Yiwis.n.mohamed',
    NULL,
    'MA',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101846332","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'suresh',
    'Drsureshs90',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018463647","content":"after 6 months he is busy with other course","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Obeida Saleh',
    'Obiedaobeidat93',
    NULL,
    'MA',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018463649","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'علي النيفرو',
    'Alialnifro20191986',
    NULL,
    'LY',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018463890","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdullah Alshadadi',
    'Alshadadia6',
    NULL,
    'EG',
    'Others',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018463640","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'اكرم رزاز العسالي',
    'Akrmmrazzz',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018463549","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Prathiksha',
    'Prathikshabharath0806',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018463324","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Anne Katherine Barros',
    'Akatherinebarros',
    NULL,
    'BR',
    'Others',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018463537","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ashraf Hosny',
    'Dr_asheraf_h',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018463169","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'عدنان عزالدين',
    'Adnan737825541',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018463435","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Anup Shyamal',
    'Drashyamal',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018463236","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Nguyen Khue',
    'Duykhuetv',
    '+84973209326',
    'VN',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018463885","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Tutan Das',
    'Dastutan92',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Warm',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018463879","content":"brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'اماني العواضي',
    'Amanidoctormaster',
    NULL,
    'US',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018463743","content":"brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Gunjankumar',
    'Raaajpandya',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Warm',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018463959","content":"Not Ans","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Esraa El Saeid',
    'Asrasaed80',
    NULL,
    'EG',
    'Others',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018463204","content":"Brochures send on whataap","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Salah Zaghloul',
    'Salahzaghloul57',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018463286","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Muhammad Zuhaid',
    'Drzuhaid61',
    NULL,
    'GB',
    'Others',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-175915101846352","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'ramy mohamed atlm',
    'Ramy.atlm',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018463808","content":"No Ans","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohammed Ibrahim',
    'Azharmahmed70',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018463401","content":"no answere text in whats up","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Murali Raj',
    'Dr.murali1983',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018463463","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr-Mahmoud Saed',
    'Dr.mahmoudsaed3838',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018463500","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'مجدي عبد المنعم',
    'Magdy.cardio',
    NULL,
    'EG',
    'Others',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018463916","content":"brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Soni Yadav',
    'Ssoni20n',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018463441","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.463Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Reffat',
    'Mohammadreffat5',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018464572","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.464Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mahmoud Sayed Baioumy',
    'Mahmoudbemox',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018464783","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.464Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohammad Hamid',
    'Dr.mhamid',
    NULL,
    'SY',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018464529","content":"Brochures send call back","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.464Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Esmail',
    'Doc.ahmed_salama',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018464283","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.464Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'سيف',
    'Seifkhaled1234',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018464560","content":"no answere text in whats up","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.464Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Wael Njeim',
    'Waelnujaim',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018464259","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.464Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Yassine Benslimane',
    'Ybenslimane98',
    NULL,
    'MA',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018464505","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.464Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sky Tr',
    'Rizwana1816ali',
    '+97455576651',
    'US',
    'MBBS/ FMG',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018464173","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.464Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Molakala Pavan Kumar Reddy',
    'Srirampawan',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018464995","content":"no answere text in whats up","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.464Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Jitendra Dutta',
    'Dr.dutta051284',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018465665","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.465Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Arshad ali',
    'Arshadalifrnd',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018465511","content":"Brochurres send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.465Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mayaank Gupta',
    'Mayankzzzzz',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018465112","content":"Brochurres send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.465Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Khaled Aly',
    'Adreno82',
    NULL,
    'EG',
    'Others',
    'Interventional',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018465961","content":"Brochurres send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.465Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Osama Al-aqel',
    'Osamaalaqel2',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018465482","content":"No what aap no","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.465Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dipendra KC',
    'Kcdipen007',
    NULL,
    'NP',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018465557","content":"RNR // RNR ( called Dr more then 5 times ) // RNR // RNR // RNR // RNR /// Busy tone","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.465Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'عبدالواحد عبدالغني البخيتي',
    'Abdon0587',
    NULL,
    'Yemen',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018466386","content":"RNR // RNR ( called Dr more then 5 times ) // RNR // RNR // RNR // RNR /// switch off","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Roshan Khadka',
    'Drroshankhadka',
    NULL,
    'NP',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018466856","content":"Line busy // Busy tone ( called Dr more then 5 times ) // Busy tone // Line busy // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'عارف الشعباني',
    'Alshabaniaref',
    NULL,
    'YE',
    'Others',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-175915101846627","content":"RNR // RNR ( called Dr more then 5 times ) // RNR // Dr answer and disconnected the call // RNR // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Kerolus Kamel',
    'Kerolusk',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018466321","content":"RNR // RNR ( called Dr more then 5 times ) RNR // RNR // RNR // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sara Abo Daif',
    'Saramohamed.s2000',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018466401","content":"Line busy // RNR ( called Dr more then 5 times ) // RNR // line busy // RNR // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Merekab',
    'Mohamedmerekab',
    NULL,
    'SA',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018466579","content":"RNR // Line busy ( called Dr more then 5 times ) // RNR // RNR / Line busy / Line busy / Line busy","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abobakr Abdalah',
    'Ab3950436',
    NULL,
    'US',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018466328","content":"RNR // Line busy ( called Dr more then 5 times ) // RNR // RNR // RNR // RNR // Line busy","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohamed Gaballah',
    'Maagaballah',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018466560","content":"RNR // RNR ( called Dr more then 5 times ) // RNR // RNR // RNR // line busy","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr.Ambedkar kumar Yadav',
    'Yadavambedkarkumar',
    NULL,
    'NP',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018466355","content":"-","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'علي حميد',
    'Alialhabashi13',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018466104","content":"RNR // RNR ( called Dr more then 5 times ) // likely fraud // RNR // Voice mail // likely fraud // likely fraud","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mahmoud Elazouny',
    'Dr.azounycardio',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018466622","content":"-","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ramy b2b',
    'Dr.ramymagdysh',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018466925","content":"-","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dares Ahmed Shams Eldin',
    'Www.d.daresaldee',
    NULL,
    'YE',
    'Others',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018466228","content":"RNR // RNR ( called Dr more then 5 times ) // RNR // RNR // RNR // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Payodh Chaudhary',
    'Drpayodhchaudhary',
    NULL,
    'US',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018466536","content":"Said not intrested in whats up","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'DrVarun Sibal',
    'Drsibalvarun',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018466404","content":"-","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Shephali Bhagat',
    'Shephalibhagat4',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-175915101846680","content":"Voice mail // Voice mail ( called Dr more then 5 times ) // Voice mail // Voice mail / Voice mail // busy tone","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Binod baduwal',
    'Bijaybaduwal',
    NULL,
    'NP',
    'Others',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-175915101846673","content":"-","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr.Binish Cheulkar',
    'Binish.cheulkar',
    NULL,
    'IN',
    'Others',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018466214","content":"-","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'faryal Khan',
    'Drfayazkhan13',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018466489","content":"RNR // Busy tone ( called Dr more then 5 times ) // No response // rnr // rnr // No response // Busy tone","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'sachin pathak',
    'Sachinpathak7719',
    NULL,
    'IN',
    'Others',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018466554","content":"-","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Aayushi Sobhani',
    'Aayushi.sobhani0',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018466827","content":"Busy tone // RNR ( called Dr more then 5 times ) // Called to Dr said want super speciality course // dr said she is looking for looking for child and adult Psychiatry","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Pratikshya Pokharel',
    'Pratikchya.pokharel',
    NULL,
    'NP',
    'Others',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018466743","content":"Said not intrested in whats up","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);
