-- IBMP Leads Import - Batch 03
-- Records: 100
-- Generated: 2025-09-29T13:18:26.727Z

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sumita_Malla',
    'Sumitathakuri48',
    NULL,
    'NP',
    'Others',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018466766","content":"RNR / RNR ( called Dr more then 5 times ) // RNR // RNR // RNR // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr. Danish Hussain',
    'Sirsayedfoundation',
    NULL,
    'IN',
    'AYUSH',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018466620","content":"Not reachabel // RNR ( called Dr more then 5 times ) // line busy // RNR // RNR // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Anjina Sapkota',
    'Anjinaspk',
    NULL,
    'NP',
    'Others',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018466855","content":"-","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'albagir Osman',
    'Bakash73',
    NULL,
    'SD',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018466201","content":"Line busy // Line busy ( called Dr more then 5 times ) // Line busy // Line busy // Line busy // Line busy // No response","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Anjan Khadka',
    'Anjankhadka14',
    NULL,
    'NP',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018466466","content":"-","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.466Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mayakrishnan Arasan',
    'Drmayakrish',
    NULL,
    'IN',
    'Others',
    'Psychiatric ads',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018467622","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr.Georgy Joseph',
    'Josephg123123',
    '9447365252',
    'IN',
    'AYUSH',
    'Psychiatric ads',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018467548","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dhakal Sujan',
    'Dhakal1234sujan',
    NULL,
    'NP',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018467256","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'drp k srivastava',
    'Praveencsrivastva',
    '9897509785',
    'IN',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Warm',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018467826","content":"he is looking for someone she is bds","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'DrVaibhav Nagur',
    'Drvaibhavnagur',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Warm',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018467251","content":"price and hospital list shared","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Deboki Chattopadhyay',
    'Deboki123',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018467675","content":"after 18 months next batch she will plan she dont have any interest","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Pooja Hardwaria',
    'Poojahardwaria',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018467965","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mousa ahmed',
    'Youfor963',
    NULL,
    'SA',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018467138","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'DrAnil Kumar',
    'Dranil0770',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018467617","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'K somu',
    'Dr.somu82',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018467174","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'T',
    'Rjaamirali84',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018467521","content":"icna","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Danish Khan',
    'Danishkhan8958474724',
    NULL,
    'IN',
    'AYUSH',
    'Psychiatric ads',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018467630","content":"call hanguped","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'آصفہ جرال',
    'Asifajaral786',
    NULL,
    'IN',
    'AYUSH',
    'Psychiatric ads',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101846792","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'santhanabharathi',
    'Santhanamgowthamar',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018467130","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Darshani Waikhom',
    'Darshaniwaikhom97',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101846764","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr.Ukasha',
    'Ukasha2050',
    NULL,
    'IN',
    'AYUSH',
    'Psychiatric ads',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018467748","content":"he said not interested in call","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ravindra Kumar Karn',
    'Karn.ravindra1210',
    NULL,
    'NP',
    'Others',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101846745","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Julia Morasutti',
    'Juliamorasutti',
    NULL,
    'BR',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018467383","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Saakshi Duggal',
    'Duggalsaakshi',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018467705","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Vivek Sharma',
    'Drsharmavivek',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018467176","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Айман Хамди',
    'Aymanomara70',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018467885","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Osama Mohy',
    'Samopharm',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018467365","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'H.M.S Tharushi Herath',
    'Tharushiherath91',
    '+94712181333',
    'LK',
    'Others',
    'Psychiatric ads',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018467980","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abhishek N R',
    'Abhishekmaestro75',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018467635","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'DARWIN',
    'Udarwin.aro',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018467142","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mahmoud Abo Elazayem',
    'Abou-elazayem',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018467417","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Priya Shrestha',
    'Priya.sth2012',
    NULL,
    'NP',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018467611","content":"Brpchures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Rajan Ramamoorthy',
    'Profraj.sugi2006',
    NULL,
    'IN',
    'Others',
    'Psychiatric ads',
    'Junk',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018467431","content":"He is not a Dr","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mahmoud Abd-Elraheem',
    'Mahmoudhegab495',
    NULL,
    'EG',
    'Others',
    'Psychiatric ads',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018467458","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr. Sakshi Anand',
    'Sakshi_anand',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018467163","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Rsp Scr',
    'Medico_ravi2000',
    '+15629249673',
    'IN',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Junk',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018467265","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Shakshi Udyan',
    'Shakshirussia',
    NULL,
    'RU',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018467581","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Nitin K. Solanki',
    'Kumarsolankinitin',
    '9928040876',
    'IN',
    'AYUSH',
    'Psychiatric ads',
    'Junk',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018467171","content":"He is student og 2 Years BYNS","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr. Dipankar Patra',
    'Dipankarpatra',
    NULL,
    'IN',
    'Others',
    'Psychiatric ads',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018467829","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'عبده عباس ناصر الهتاري',
    'Salh5577813',
    NULL,
    'US',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018467627","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ali Humaid',
    'Alijameelhomaid',
    NULL,
    'YE',
    'Others',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018467131","content":"he is speaking arabic he said to share me in wtsapp with mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'عبدالصمد أحمد علي صقير قاسم',
    'Ly2956139',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018467465","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'DrBam Bahadur Singh',
    'Drbambahadursingh123',
    NULL,
    'NP',
    'AYUSH',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018467210","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr Parami Gunasekara',
    'Spgunasekera',
    '+94777908117',
    'LK',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018467791","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Aman Singh',
    'Rs431140',
    NULL,
    'IN',
    'AYUSH',
    'Psychiatric ads',
    'Junk',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018467641","content":"she is not a doctor","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr. Gurdarshan Singh Bhambra',
    'Dr_bhambra',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018467376","content":"around july he will enroll next year","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Nikitha Beeram',
    'Nikithareddybeeram',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018467985","content":"call hanguping every time","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.467Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'GLCV Liyanage',
    'Chinthana.viraj',
    '+94773772540',
    'LK',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101846855","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mona Nk',
    'Mona_nk1',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018468992","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'RAHUL KEWAL KUMAR',
    'Drrahulkkg',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018468755","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dipak Gharzode',
    'Dipakgharzode82',
    NULL,
    'IN',
    'AYUSH',
    'Psychiatric ads',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018468585","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'ikram.RH',
    'Ikramrhars.777',
    NULL,
    'MA',
    'Others',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018468867","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr.Mohamed Mahrous',
    'Mhmmahrous',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018468607","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'DrBhagwat Rajput',
    'Dr.bhagwat.cordinator',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018468469","content":"Not Interested dont want to do patients is near to me call hanguped","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Atul Yadav',
    'Medicoatulyadav945',
    NULL,
    'IN',
    'Others',
    'Psychiatric ads',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018468680","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Narendra kumar Shah',
    'Narendrashah107',
    NULL,
    'NP',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018468581","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'butterfly',
    'Nijashahi',
    NULL,
    'US',
    'Others',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018468410","content":"Said not intrested said not a Dr","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Jitendra Kumar Singh',
    'Jsingdj',
    NULL,
    'NP',
    'Others',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018468736","content":"Said not intrested in whats up","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Prashant Shukla',
    'Panditprashantshukla',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018468347","content":"-","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Puang Achock Matajang',
    'Azlee8588',
    '+60175535813',
    'MY',
    'Others',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018468612","content":"Busy tone // RNR ( called Dr more then 5 times ) // RNR // RNR // Busy tone / Tried to connect many times no answer / RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Manoj Prajapati',
    'Manojprajapati6176',
    NULL,
    'IN',
    'AYUSH',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018468766","content":"Not reachabel // Called answer by 3 rd person Dr not there // RNR // Line busy // Tried to connect many times no answer likely farud // Tried to connect many times no answer likely farud","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Zynab salman',
    'Zynabsalman',
    '+94763107106',
    'LK',
    'Others',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018468538","content":"Said not intrested in whats up","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sandeep Gambhir',
    'Sandeepgambhir',
    '6583219235',
    'IN',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018468991","content":"RNR // RNR ( called Dr more then 5 times ) // RNR // RNR // RNR // Tried to connect many times no answer // Not available","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Rakesh Chaurasiya',
    'Rocky_themalefactor',
    NULL,
    'NP',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018468923","content":"RNR // RNR ( called Dr more then 5 times ) // Busy tone // RNR // Call answer and disconnected // Tried to connect many times no answer // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'സൂപ്പർ ഈഗോ സൈക്കോളജിക്കൽ സർവീസസ്',
    'Jithink4u',
    NULL,
    'IN',
    'AYUSH',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018468810","content":"Voice mail // Voice mail ( called Dr more then 5 times ) // Voice mail // Voice mail // Call answer and disconnected the call // Tried to connect many times no answer // not available // Voice mail","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Bhupendra Gurung',
    'Bhupendrapahachyu',
    NULL,
    'NP',
    'Others',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018468801","content":"RNR // Busy line ( called Dr more then 5 times ) // Busy line // RNR // RNR // Tried to connect many times no answer // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abrar Ul',
    'Abrar_2689',
    NULL,
    'US',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018468861","content":"RNR // Dr called back and disconnected the call // Busy tone ( called Dr more then 5 times ) // Busy tone // RNR // Busy tone // rnr // RNR","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'S. Hussain',
    'Hussaindr016',
    NULL,
    'US',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018468570","content":"Dr answred and said he will only call and disconnected the call // Call answered and disconnected the call // RNR // Busy in other call // DR Answer the said not intrested for the course","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sumith Koshy',
    'Kewlsumato',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018468920","content":"Not reachabel // Line busy ( called Dr more then 5 times ) // Not reachabel // Not reachabel // line busy","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Avijit Raha',
    'Avijit.raha',
    NULL,
    'IN',
    'Others',
    'Psychiatric ads',
    'Not Interested',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018468748","content":"Not reachabel // Not reachabel ( called Dr more then 5 times ) // Not reachabel // Not reachabel // Not reachabel // Not reachabel","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Waleed Kassim',
    'Kassimameen2',
    NULL,
    'YE',
    'Others',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018468343","content":"he is speaking arabic he said to share me in wtsapp with mam number","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Anoop vithayathil',
    'Anoopjaine4sik',
    NULL,
    'IN',
    'Others',
    'Psychiatric ads',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018468235","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Majeed Ansari',
    'Majeed3699',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Not Interested',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018468428","content":"icna","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Venkata Ramana Reddy Ganta',
    'Grreddy13',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Warm',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018468650","content":"family medicine fellowship","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Маюран Понраса',
    'Pmauran8787',
    '+94750775122',
    'LK',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018468636","content":"after a week he will come back to his country","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Samiera Ibrahim Hassn Abzid',
    'Samiera61',
    NULL,
    'US',
    'MBBS/ FMG',
    'Psychiatric ads',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018468818","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abhishek W Evans',
    'Abhishekwevans1994',
    NULL,
    'IN',
    'Others',
    'Fellowship Psyc',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018468185","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Bollam Prince',
    'Princebollam1',
    NULL,
    'IN',
    'Others',
    'Fellowship Psyc',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018468175","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Choudhary Asad Ahmad Khan',
    'Imasmadkhan',
    NULL,
    'IN',
    'AYUSH',
    'Fellowship Psyc',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018468338","content":"Bhms He did genral inquries","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr-Abdullah Yusef',
    'Abdullah2016yusef',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018468668","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.468Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr. Jyoti Jogdand',
    'Yogitajogdand88',
    NULL,
    'IN',
    'AYUSH',
    'Fellowship Psyc',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018469251","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.469Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Murali Challa',
    'Mchalla3113',
    NULL,
    'IN',
    'Others',
    'Fellowship Psyc',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018469720","content":"Not connecting","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.469Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Prekshya Khatiwada',
    'Prekshya055',
    NULL,
    'NP',
    'Others',
    'Fellowship Psyc',
    'Junk',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018469278","content":"She is not a Dr nurse","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.469Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Randika K. Hannadige',
    'Krshannadige',
    '+94776629699',
    'LK',
    'MBBS/ FMG',
    'Fellowship Psyc',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018469926","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.469Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Rupendra Kumar Patel',
    'Roopendrakumarr',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Fellowship Psyc',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018469111","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.469Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Syed Kashif Ur Rahman',
    'Syedkashifurrahman622',
    NULL,
    'MY',
    'MBBS/ FMG',
    'Interventional',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018469903","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.469Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sakshi Gupta',
    'Tina.hbkcap',
    '7888967328',
    'IN',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018469597","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.469Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'mohd vaqui',
    'Vaqui0786',
    NULL,
    'IN',
    'AYUSH',
    'Psychiatric ads',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018469781","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.469Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Rohith Reddy',
    'Rohit.rebu',
    NULL,
    'IN',
    'MD/MS/DNB',
    'Psychiatric ads',
    'Not Interested',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018469634","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.469Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Kundan kumar',
    'Sabkundan80',
    NULL,
    'IN',
    'Others',
    'Cardiology ad',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018469901","content":"call hanguped","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.469Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'PERAMUNE Arachchillage Bandupriya Bandara Peramune',
    'Bbpa7',
    '+94710105834',
    'LK',
    'Others',
    'Cardiology ad',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018469773","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.469Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    '𝘿𝙧.𝙇𝙖𝙫𝙞𝙨𝙝',
    'Lavish.wonderboy',
    NULL,
    'IN',
    'MD/MS/DNB',
    'family medicine',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018469521","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.469Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dhiraj salunke',
    'Sakalsalunke',
    NULL,
    'IN',
    'Others',
    'Cardiology ad',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018469916","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.469Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Krithika | premium lifestyle blogger | Coimbatore ',
    'Krithikavaradharaj06',
    NULL,
    'IN',
    'Others',
    'Cardiology ad',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018469100","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.469Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hajra Khan',
    'Aslamzk24',
    NULL,
    'IN',
    'Others',
    'Cardiology ad',
    'Follow Up',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018469457","content":"Not answering","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.469Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'JATIN SONKAR',
    'Jatinsonkar48',
    NULL,
    'IN',
    'Others',
    'Critical care a',
    'Junk',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018469461","content":"He is not a Dr","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.469Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    '×͜× Rɪᴛᴜ Mᴇɢʜʀᴀᴊ ×͜×',
    'Sarvanmeghwanshi33',
    NULL,
    'IN',
    'Others',
    'Critical care a',
    'Junk',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018469407","content":"He is not a Dr","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.469Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ebrahem M. Elbassuny',
    'Bassunyebrahem',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Critical care a',
    'Follow Up',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018469758","content":"Brochures send","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.469Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Zouhir Don',
    'Chaymaekhaldon',
    NULL,
    'US',
    'Others',
    'Critical care a',
    'Junk',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018469811","content":"Call hang up","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.469Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Rupendra Kanjar',
    'Rupendrakanjar2',
    NULL,
    'US',
    'Others',
    'Critical care a',
    'Junk',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018469644","content":"He is not a Dr","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.469Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);
