-- IBMP Leads Import - Batch 12
-- Records: 56
-- Generated: 2025-09-29T13:18:26.735Z

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Yaseen.A',
    'Alaswadyaseen2',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476284","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Adel Alhaj',
    'Adelygh7',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476432","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Yasin Alhasan',
    '5751198y',
    NULL,
    'SA',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476895","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohab Elzahed',
    'Mohabameen.ma.ma99',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476988","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Oussama Sidaty',
    'Ousssid',
    NULL,
    'MA',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101847624","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Merhan Mohamed',
    'Drmerynagary',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476602","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Elkennassi fayssal',
    'Elkennassi',
    NULL,
    'MA',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476193","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    '𝙳𝚛.𝚙𝚛𝚒𝚝𝚊𝚖 𝚜𝚊𝚠𝚊𝚗𝚝',
    'Sawantpritam422000',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476922","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Imali Wijerathne',
    'Imalimw',
    '+94714440465',
    'LK',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476649","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr sandeep walia',
    'Sandeepwalia1919',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476126","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ahmed Mohammad',
    'Am1905820',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476779","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mridul Panwar',
    'Panwarmridul1998',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476132","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Marah Arsalan AL-tayeb',
    'Maraharsalanaltayp',
    NULL,
    'YE',
    'Others',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476150","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'இராமசாமி பாலசுப்பிரமணியன்',
    'Bramasamy880',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476144","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr.darioush',
    'Darioush7777',
    '+37495645905',
    'IR',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-175915101847665","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'NISARG',
    'Nisarg431001',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476340","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Soliman Elshahat',
    'Sulaiman.elshahat',
    NULL,
    'SA',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Nakshatra',
    'IBMP',
    '[{"id":"note-1759151018476970","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Nakshatra',
    'Nakshatra',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Taha Mohammed Muhsen Eshaih',
    'Taha55860',
    NULL,
    'YE',
    'Others',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476235","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ashraff izzathul Muneera',
    'Ashraffmuneera678',
    '+94761024009',
    'LK',
    'AYUSH',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476640","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ꮦ Ꮼ Ꮥ Ꮒ Ꮧ Ꮢ',
    'Smartboytushar2020',
    NULL,
    'US',
    'AYUSH',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476930","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Kholod Monir',
    'Kholodmonir7',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476510","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr.Gufran Chaudhary',
    'Gufrankhan96340',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476535","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Aditya Sahu',
    'Adityasahu68195',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476455","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Khemraj Adhikari',
    'Akhemraj07',
    NULL,
    'NP',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476564","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'karrtik',
    'Rahulpatil98',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476166","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ժենյա Արամյան',
    'Zhenya.aramyan',
    '+37491021498',
    'AM',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476926","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Hitarth Vyas',
    'Hitarthvyas66',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476989","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mhdsabri Hassan',
    'Gabton',
    '+60102803231',
    'MY',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-175915101847655","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Pramisha Giri',
    'Nepalipathekali123',
    NULL,
    'NP',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476855","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Pragesh Mahato',
    'Doc.prageshmahato77',
    NULL,
    'NP',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Aslam',
    'IBMP',
    '[{"id":"note-1759151018476894","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Aslam',
    'Aslam',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Vethaoli Ayush Centre',
    'Vsfb78',
    NULL,
    'US',
    'AYUSH',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-17591510184760","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ashok Todkar',
    'Dr.ashoktodkar97',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476261","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr. Rajeev Mishra',
    'Rajumishra010397',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476148","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Wafaa Taher',
    'Wafa1977',
    NULL,
    'YE',
    'Others',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476608","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr-Ismail AlShoaibi',
    'Drismsho',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-175915101847690","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr harshu Sharma',
    'Harshus062',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476328","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mahinda Wanisundara',
    'Wanisundaram',
    '+94718108127',
    'LK',
    'Others',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476968","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'DanaseSudarsan babu',
    'Dsudarshanbabu1985',
    '+17013485893',
    'US',
    'AYUSH',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476484","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr-Ahmad',
    'Drahmadcardio',
    NULL,
    'GB',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476500","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Dr.a_dhanush',
    'Kumardhanush01534',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476384","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'شمسان جعفر',
    'Sjaffar135',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476404","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Parul Wadhwa',
    'Drpardeepwadhwa',
    NULL,
    'IN',
    'AYUSH',
    'Interventional',
    'Fresh',
    'Roshan',
    'IBMP',
    '[{"id":"note-1759151018476636","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Roshan',
    'Roshan',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Wael Hasseb',
    'Wael372002',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476567","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mohammed Alezzi Mudhsh',
    'Mamda1510',
    NULL,
    'YE',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-175915101847638","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mahmoud Mohamed',
    'Ma01065m',
    NULL,
    'EG',
    'Others',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476920","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Mansour Aref El-aser',
    'Mans_aref',
    NULL,
    'EG',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476160","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Tasneem Mohamed',
    'Tykassem',
    NULL,
    'EG',
    'Others',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476615","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'karima benbouchta',
    'Karima_22',
    NULL,
    'US',
    'Others',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476690","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'rama',
    'Rama786jkp9',
    NULL,
    'IN',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-175915101847657","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Abdalla wagialla',
    'Abooody24',
    NULL,
    'AE',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-17591510184767","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Israa Es-safar',
    'Essafarisraa',
    NULL,
    'MA',
    'Others',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476768","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    '𝚆𝙴𝙳𝙸𝙰𝙽 || وديان',
    'Dd8512910',
    NULL,
    'EG',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476476","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Bashar Aldilamy',
    'Bsharaldylmy729',
    NULL,
    'YE',
    'MD/MS/DNB',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476957","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Ayat',
    'Khatoonsakina058',
    NULL,
    'IN',
    'Others',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476119","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'oukhlift hafid',
    'Hafiddok',
    NULL,
    'MA',
    'MBBS/ FMG',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476906","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);

INSERT INTO "public"."leads" (
    "fullName", 
    "email", 
    "phone", 
    "country", 
    "qualification", 
    "course", 
    "status", 
    "assignedTo", 
    "source",
    "notes",
    "priority",
    "score",
    "experience",
    "location",
    "communicationscount",
    "assigned_to",
    "assignedcounselor",
    "tags",
    "custom_fields",
    "createdAt",
    "updatedAt",
    "created_at",
    "updated_at",
    "updated_by"
) VALUES (
    'Sma Ali',
    'Najmhuda560',
    NULL,
    'US',
    'Others',
    'Interventional',
    'Fresh',
    'Satish',
    'IBMP',
    '[{"id":"note-1759151018476619","content":"Imported from IBMP database","author":"IBMP Import","timestamp":"2025-09-29T13:03:38.476Z","note_type":"general"}]',
    'medium',
    '50',
    'Not specified',
    'Not specified',
    '0',
    'Satish',
    'Satish',
    NULL,
    '{}',
    now(),
    now(),
    now(),
    now(),
    'System'
);
